/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DepartmentDTO,
  DepartmentRequest,
} from '../models/index';
import {
    DepartmentDTOFromJSON,
    DepartmentDTOToJSON,
    DepartmentRequestFromJSON,
    DepartmentRequestToJSON,
} from '../models/index';

export interface DepartmentCreateRequest {
    companyId: number;
    departmentRequest: DepartmentRequest;
}

export interface DepartmentDeleteRequest {
    id: number;
}

export interface DepartmentGetByIdRequest {
    id: number;
}

export interface DepartmentGetDepartmentsByCompanyRequest {
    companyId: number;
}

export interface DepartmentUpdateRequest {
    id: number;
    departmentRequest: DepartmentRequest;
}

/**
 * DepartmentsApi - interface
 * 
 * @export
 * @interface DepartmentsApiInterface
 */
export interface DepartmentsApiInterface {
    /**
     * 
     * @summary Create department
     * @param {number} companyId 
     * @param {DepartmentRequest} departmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    departmentCreateRaw(requestParameters: DepartmentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>>;

    /**
     * Create department
     */
    departmentCreate(requestParameters: DepartmentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO>;

    /**
     * 
     * @summary Delete department
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    departmentDeleteRaw(requestParameters: DepartmentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete department
     */
    departmentDelete(requestParameters: DepartmentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get department by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    departmentGetByIdRaw(requestParameters: DepartmentGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>>;

    /**
     * Get department by id
     */
    departmentGetById(requestParameters: DepartmentGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO>;

    /**
     * 
     * @summary Get departments by company
     * @param {number} companyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    departmentGetDepartmentsByCompanyRaw(requestParameters: DepartmentGetDepartmentsByCompanyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DepartmentDTO>>>;

    /**
     * Get departments by company
     */
    departmentGetDepartmentsByCompany(requestParameters: DepartmentGetDepartmentsByCompanyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DepartmentDTO>>;

    /**
     * 
     * @summary Update department
     * @param {number} id 
     * @param {DepartmentRequest} departmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    departmentUpdateRaw(requestParameters: DepartmentUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>>;

    /**
     * Update department
     */
    departmentUpdate(requestParameters: DepartmentUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO>;

}

/**
 * 
 */
export class DepartmentsApi extends runtime.BaseAPI implements DepartmentsApiInterface {

    /**
     * Create department
     */
    async departmentCreateRaw(requestParameters: DepartmentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>> {
        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling departmentCreate().'
            );
        }

        if (requestParameters['departmentRequest'] == null) {
            throw new runtime.RequiredError(
                'departmentRequest',
                'Required parameter "departmentRequest" was null or undefined when calling departmentCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/companies/{companyId}/departments`.replace(`{${"companyId"}}`, encodeURIComponent(String(requestParameters['companyId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DepartmentRequestToJSON(requestParameters['departmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentDTOFromJSON(jsonValue));
    }

    /**
     * Create department
     */
    async departmentCreate(requestParameters: DepartmentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO> {
        const response = await this.departmentCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete department
     */
    async departmentDeleteRaw(requestParameters: DepartmentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling departmentDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/departments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete department
     */
    async departmentDelete(requestParameters: DepartmentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.departmentDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get department by id
     */
    async departmentGetByIdRaw(requestParameters: DepartmentGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling departmentGetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/departments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentDTOFromJSON(jsonValue));
    }

    /**
     * Get department by id
     */
    async departmentGetById(requestParameters: DepartmentGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO> {
        const response = await this.departmentGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get departments by company
     */
    async departmentGetDepartmentsByCompanyRaw(requestParameters: DepartmentGetDepartmentsByCompanyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DepartmentDTO>>> {
        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling departmentGetDepartmentsByCompany().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/companies/{companyId}/departments`.replace(`{${"companyId"}}`, encodeURIComponent(String(requestParameters['companyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DepartmentDTOFromJSON));
    }

    /**
     * Get departments by company
     */
    async departmentGetDepartmentsByCompany(requestParameters: DepartmentGetDepartmentsByCompanyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DepartmentDTO>> {
        const response = await this.departmentGetDepartmentsByCompanyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update department
     */
    async departmentUpdateRaw(requestParameters: DepartmentUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling departmentUpdate().'
            );
        }

        if (requestParameters['departmentRequest'] == null) {
            throw new runtime.RequiredError(
                'departmentRequest',
                'Required parameter "departmentRequest" was null or undefined when calling departmentUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/departments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DepartmentRequestToJSON(requestParameters['departmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentDTOFromJSON(jsonValue));
    }

    /**
     * Update department
     */
    async departmentUpdate(requestParameters: DepartmentUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO> {
        const response = await this.departmentUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
