/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DocumentGroupDTO,
  DocumentGroupRequest,
  DocumentSummaryDTO,
} from '../models/index';
import {
    DocumentGroupDTOFromJSON,
    DocumentGroupDTOToJSON,
    DocumentGroupRequestFromJSON,
    DocumentGroupRequestToJSON,
    DocumentSummaryDTOFromJSON,
    DocumentSummaryDTOToJSON,
} from '../models/index';

export interface DocumentGroupCreateGroupRequest {
    documentGroupRequest: DocumentGroupRequest;
}

export interface DocumentGroupDeleteGroupRequest {
    groupId: number;
}

export interface DocumentGroupGetDocumentsInGroupRequest {
    groupId: number;
}

/**
 * DocumentGroupsApi - interface
 * 
 * @export
 * @interface DocumentGroupsApiInterface
 */
export interface DocumentGroupsApiInterface {
    /**
     * 
     * @summary Create document group
     * @param {DocumentGroupRequest} documentGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentGroupsApiInterface
     */
    documentGroupCreateGroupRaw(requestParameters: DocumentGroupCreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentGroupDTO>>;

    /**
     * Create document group
     */
    documentGroupCreateGroup(requestParameters: DocumentGroupCreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentGroupDTO>;

    /**
     * 
     * @summary Delete document group
     * @param {number} groupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentGroupsApiInterface
     */
    documentGroupDeleteGroupRaw(requestParameters: DocumentGroupDeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete document group
     */
    documentGroupDeleteGroup(requestParameters: DocumentGroupDeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get all document groups
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentGroupsApiInterface
     */
    documentGroupGetAllGroupsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DocumentGroupDTO>>>;

    /**
     * Get all document groups
     */
    documentGroupGetAllGroups(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DocumentGroupDTO>>;

    /**
     * 
     * @summary Get the documents in a document group
     * @param {number} groupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentGroupsApiInterface
     */
    documentGroupGetDocumentsInGroupRaw(requestParameters: DocumentGroupGetDocumentsInGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DocumentSummaryDTO>>>;

    /**
     * Get the documents in a document group
     */
    documentGroupGetDocumentsInGroup(requestParameters: DocumentGroupGetDocumentsInGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DocumentSummaryDTO>>;

}

/**
 * 
 */
export class DocumentGroupsApi extends runtime.BaseAPI implements DocumentGroupsApiInterface {

    /**
     * Create document group
     */
    async documentGroupCreateGroupRaw(requestParameters: DocumentGroupCreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentGroupDTO>> {
        if (requestParameters['documentGroupRequest'] == null) {
            throw new runtime.RequiredError(
                'documentGroupRequest',
                'Required parameter "documentGroupRequest" was null or undefined when calling documentGroupCreateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/document-groups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentGroupRequestToJSON(requestParameters['documentGroupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentGroupDTOFromJSON(jsonValue));
    }

    /**
     * Create document group
     */
    async documentGroupCreateGroup(requestParameters: DocumentGroupCreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentGroupDTO> {
        const response = await this.documentGroupCreateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete document group
     */
    async documentGroupDeleteGroupRaw(requestParameters: DocumentGroupDeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling documentGroupDeleteGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/document-groups/{groupId}`.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete document group
     */
    async documentGroupDeleteGroup(requestParameters: DocumentGroupDeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.documentGroupDeleteGroupRaw(requestParameters, initOverrides);
    }

    /**
     * Get all document groups
     */
    async documentGroupGetAllGroupsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DocumentGroupDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/document-groups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentGroupDTOFromJSON));
    }

    /**
     * Get all document groups
     */
    async documentGroupGetAllGroups(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DocumentGroupDTO>> {
        const response = await this.documentGroupGetAllGroupsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the documents in a document group
     */
    async documentGroupGetDocumentsInGroupRaw(requestParameters: DocumentGroupGetDocumentsInGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DocumentSummaryDTO>>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling documentGroupGetDocumentsInGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/document-groups/{groupId}/documents`.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentSummaryDTOFromJSON));
    }

    /**
     * Get the documents in a document group
     */
    async documentGroupGetDocumentsInGroup(requestParameters: DocumentGroupGetDocumentsInGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DocumentSummaryDTO>> {
        const response = await this.documentGroupGetDocumentsInGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
