/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CancelProcessInstanceRequest,
  ProcessInstanceDTO,
  StartProcessInstanceRequest,
} from '../models/index';
import {
    CancelProcessInstanceRequestFromJSON,
    CancelProcessInstanceRequestToJSON,
    ProcessInstanceDTOFromJSON,
    ProcessInstanceDTOToJSON,
    StartProcessInstanceRequestFromJSON,
    StartProcessInstanceRequestToJSON,
} from '../models/index';

export interface ProcessInstanceCancelRequest {
    id: string;
    cancelProcessInstanceRequest?: CancelProcessInstanceRequest;
}

export interface ProcessInstanceGetRequest {
    id: string;
}

export interface ProcessInstanceGetForProjectRequest {
    projectId: number;
}

export interface ProcessInstanceGetForTaskRequest {
    taskId: number;
}

export interface ProcessInstanceStartForProjectRequest {
    projectId: number;
    startProcessInstanceRequest: StartProcessInstanceRequest;
}

export interface ProcessInstanceStartForTaskRequest {
    taskId: number;
    startProcessInstanceRequest: StartProcessInstanceRequest;
}

/**
 * ProcessInstancesApi - interface
 * 
 * @export
 * @interface ProcessInstancesApiInterface
 */
export interface ProcessInstancesApiInterface {
    /**
     * 
     * @summary Stops a running instance
     * @param {string} id 
     * @param {CancelProcessInstanceRequest} [cancelProcessInstanceRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessInstancesApiInterface
     */
    processInstanceCancelRaw(requestParameters: ProcessInstanceCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Stops a running instance
     */
    processInstanceCancel(requestParameters: ProcessInstanceCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary A single instance by its engine id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessInstancesApiInterface
     */
    processInstanceGetRaw(requestParameters: ProcessInstanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>>;

    /**
     * A single instance by its engine id
     */
    processInstanceGet(requestParameters: ProcessInstanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO>;

    /**
     * 
     * @summary All instances belonging to a project — its own and those of its tasks, running or finished
     * @param {number} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessInstancesApiInterface
     */
    processInstanceGetForProjectRaw(requestParameters: ProcessInstanceGetForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProcessInstanceDTO>>>;

    /**
     * All instances belonging to a project — its own and those of its tasks, running or finished
     */
    processInstanceGetForProject(requestParameters: ProcessInstanceGetForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProcessInstanceDTO>>;

    /**
     * 
     * @summary The instance a task is linked to
     * @param {number} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessInstancesApiInterface
     */
    processInstanceGetForTaskRaw(requestParameters: ProcessInstanceGetForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>>;

    /**
     * The instance a task is linked to
     */
    processInstanceGetForTask(requestParameters: ProcessInstanceGetForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO>;

    /**
     * 
     * @summary Starts a process for a whole project
     * @param {number} projectId 
     * @param {StartProcessInstanceRequest} startProcessInstanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessInstancesApiInterface
     */
    processInstanceStartForProjectRaw(requestParameters: ProcessInstanceStartForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>>;

    /**
     * Starts a process for a whole project
     */
    processInstanceStartForProject(requestParameters: ProcessInstanceStartForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO>;

    /**
     * 
     * @summary Starts a process for a single task and links the two
     * @param {number} taskId 
     * @param {StartProcessInstanceRequest} startProcessInstanceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessInstancesApiInterface
     */
    processInstanceStartForTaskRaw(requestParameters: ProcessInstanceStartForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>>;

    /**
     * Starts a process for a single task and links the two
     */
    processInstanceStartForTask(requestParameters: ProcessInstanceStartForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO>;

}

/**
 * 
 */
export class ProcessInstancesApi extends runtime.BaseAPI implements ProcessInstancesApiInterface {

    /**
     * Stops a running instance
     */
    async processInstanceCancelRaw(requestParameters: ProcessInstanceCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling processInstanceCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/process-instances/{id}/cancel`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CancelProcessInstanceRequestToJSON(requestParameters['cancelProcessInstanceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stops a running instance
     */
    async processInstanceCancel(requestParameters: ProcessInstanceCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.processInstanceCancelRaw(requestParameters, initOverrides);
    }

    /**
     * A single instance by its engine id
     */
    async processInstanceGetRaw(requestParameters: ProcessInstanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling processInstanceGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/process-instances/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessInstanceDTOFromJSON(jsonValue));
    }

    /**
     * A single instance by its engine id
     */
    async processInstanceGet(requestParameters: ProcessInstanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO> {
        const response = await this.processInstanceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * All instances belonging to a project — its own and those of its tasks, running or finished
     */
    async processInstanceGetForProjectRaw(requestParameters: ProcessInstanceGetForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProcessInstanceDTO>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling processInstanceGetForProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/process-instances`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProcessInstanceDTOFromJSON));
    }

    /**
     * All instances belonging to a project — its own and those of its tasks, running or finished
     */
    async processInstanceGetForProject(requestParameters: ProcessInstanceGetForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProcessInstanceDTO>> {
        const response = await this.processInstanceGetForProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The instance a task is linked to
     */
    async processInstanceGetForTaskRaw(requestParameters: ProcessInstanceGetForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling processInstanceGetForTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{taskId}/process-instance`.replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessInstanceDTOFromJSON(jsonValue));
    }

    /**
     * The instance a task is linked to
     */
    async processInstanceGetForTask(requestParameters: ProcessInstanceGetForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO> {
        const response = await this.processInstanceGetForTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Starts a process for a whole project
     */
    async processInstanceStartForProjectRaw(requestParameters: ProcessInstanceStartForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling processInstanceStartForProject().'
            );
        }

        if (requestParameters['startProcessInstanceRequest'] == null) {
            throw new runtime.RequiredError(
                'startProcessInstanceRequest',
                'Required parameter "startProcessInstanceRequest" was null or undefined when calling processInstanceStartForProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/process-instances`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartProcessInstanceRequestToJSON(requestParameters['startProcessInstanceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessInstanceDTOFromJSON(jsonValue));
    }

    /**
     * Starts a process for a whole project
     */
    async processInstanceStartForProject(requestParameters: ProcessInstanceStartForProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO> {
        const response = await this.processInstanceStartForProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Starts a process for a single task and links the two
     */
    async processInstanceStartForTaskRaw(requestParameters: ProcessInstanceStartForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessInstanceDTO>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling processInstanceStartForTask().'
            );
        }

        if (requestParameters['startProcessInstanceRequest'] == null) {
            throw new runtime.RequiredError(
                'startProcessInstanceRequest',
                'Required parameter "startProcessInstanceRequest" was null or undefined when calling processInstanceStartForTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{taskId}/process-instances`.replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartProcessInstanceRequestToJSON(requestParameters['startProcessInstanceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessInstanceDTOFromJSON(jsonValue));
    }

    /**
     * Starts a process for a single task and links the two
     */
    async processInstanceStartForTask(requestParameters: ProcessInstanceStartForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessInstanceDTO> {
        const response = await this.processInstanceStartForTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
