/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProcessDefinitionDTO,
} from '../models/index';
import {
    ProcessDefinitionDTOFromJSON,
    ProcessDefinitionDTOToJSON,
} from '../models/index';

export interface ProcessDefinitionActivateRequest {
    id: number;
}

export interface ProcessDefinitionDeactivateRequest {
    id: number;
}

export interface ProcessDefinitionGetRequest {
    id: number;
}

export interface ProcessDefinitionRegisterRequest {
    documentInfoId: number;
}

export interface ProcessDefinitionUnregisterRequest {
    id: number;
    force?: boolean;
}

/**
 * ProcessDefinitionsApi - interface
 * 
 * @export
 * @interface ProcessDefinitionsApiInterface
 */
export interface ProcessDefinitionsApiInterface {
    /**
     * 
     * @summary Activate a definition (deploy it to the engine and make it startable)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessDefinitionsApiInterface
     */
    processDefinitionActivateRaw(requestParameters: ProcessDefinitionActivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>>;

    /**
     * Activate a definition (deploy it to the engine and make it startable)
     */
    processDefinitionActivate(requestParameters: ProcessDefinitionActivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO>;

    /**
     * 
     * @summary Deactivate a definition (stop new instances; running ones continue)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessDefinitionsApiInterface
     */
    processDefinitionDeactivateRaw(requestParameters: ProcessDefinitionDeactivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>>;

    /**
     * Deactivate a definition (stop new instances; running ones continue)
     */
    processDefinitionDeactivate(requestParameters: ProcessDefinitionDeactivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO>;

    /**
     * 
     * @summary Get a process definition
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessDefinitionsApiInterface
     */
    processDefinitionGetRaw(requestParameters: ProcessDefinitionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>>;

    /**
     * Get a process definition
     */
    processDefinitionGet(requestParameters: ProcessDefinitionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO>;

    /**
     * 
     * @summary List all process definitions (deployed or draft)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessDefinitionsApiInterface
     */
    processDefinitionGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProcessDefinitionDTO>>>;

    /**
     * List all process definitions (deployed or draft)
     */
    processDefinitionGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProcessDefinitionDTO>>;

    /**
     * 
     * @summary Register a document as a process definition (draft, not yet deployed)
     * @param {number} documentInfoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessDefinitionsApiInterface
     */
    processDefinitionRegisterRaw(requestParameters: ProcessDefinitionRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>>;

    /**
     * Register a document as a process definition (draft, not yet deployed)
     */
    processDefinitionRegister(requestParameters: ProcessDefinitionRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO>;

    /**
     * 
     * @summary Remove a definition (drafts freely; deployed only with ?force=true)
     * @param {number} id 
     * @param {boolean} [force] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessDefinitionsApiInterface
     */
    processDefinitionUnregisterRaw(requestParameters: ProcessDefinitionUnregisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Remove a definition (drafts freely; deployed only with ?force=true)
     */
    processDefinitionUnregister(requestParameters: ProcessDefinitionUnregisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ProcessDefinitionsApi extends runtime.BaseAPI implements ProcessDefinitionsApiInterface {

    /**
     * Activate a definition (deploy it to the engine and make it startable)
     */
    async processDefinitionActivateRaw(requestParameters: ProcessDefinitionActivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling processDefinitionActivate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/process-definitions/{id}/activate`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessDefinitionDTOFromJSON(jsonValue));
    }

    /**
     * Activate a definition (deploy it to the engine and make it startable)
     */
    async processDefinitionActivate(requestParameters: ProcessDefinitionActivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO> {
        const response = await this.processDefinitionActivateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivate a definition (stop new instances; running ones continue)
     */
    async processDefinitionDeactivateRaw(requestParameters: ProcessDefinitionDeactivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling processDefinitionDeactivate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/process-definitions/{id}/deactivate`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessDefinitionDTOFromJSON(jsonValue));
    }

    /**
     * Deactivate a definition (stop new instances; running ones continue)
     */
    async processDefinitionDeactivate(requestParameters: ProcessDefinitionDeactivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO> {
        const response = await this.processDefinitionDeactivateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a process definition
     */
    async processDefinitionGetRaw(requestParameters: ProcessDefinitionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling processDefinitionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/process-definitions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessDefinitionDTOFromJSON(jsonValue));
    }

    /**
     * Get a process definition
     */
    async processDefinitionGet(requestParameters: ProcessDefinitionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO> {
        const response = await this.processDefinitionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all process definitions (deployed or draft)
     */
    async processDefinitionGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProcessDefinitionDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/process-definitions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProcessDefinitionDTOFromJSON));
    }

    /**
     * List all process definitions (deployed or draft)
     */
    async processDefinitionGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProcessDefinitionDTO>> {
        const response = await this.processDefinitionGetAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register a document as a process definition (draft, not yet deployed)
     */
    async processDefinitionRegisterRaw(requestParameters: ProcessDefinitionRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessDefinitionDTO>> {
        if (requestParameters['documentInfoId'] == null) {
            throw new runtime.RequiredError(
                'documentInfoId',
                'Required parameter "documentInfoId" was null or undefined when calling processDefinitionRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/documents/{documentInfoId}/process-definition`.replace(`{${"documentInfoId"}}`, encodeURIComponent(String(requestParameters['documentInfoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessDefinitionDTOFromJSON(jsonValue));
    }

    /**
     * Register a document as a process definition (draft, not yet deployed)
     */
    async processDefinitionRegister(requestParameters: ProcessDefinitionRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessDefinitionDTO> {
        const response = await this.processDefinitionRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a definition (drafts freely; deployed only with ?force=true)
     */
    async processDefinitionUnregisterRaw(requestParameters: ProcessDefinitionUnregisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling processDefinitionUnregister().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/process-definitions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a definition (drafts freely; deployed only with ?force=true)
     */
    async processDefinitionUnregister(requestParameters: ProcessDefinitionUnregisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.processDefinitionUnregisterRaw(requestParameters, initOverrides);
    }

}
