/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GoalRequest,
  ProjectGoalDTO,
  ProjectProgress,
} from '../models/index';
import {
    GoalRequestFromJSON,
    GoalRequestToJSON,
    ProjectGoalDTOFromJSON,
    ProjectGoalDTOToJSON,
    ProjectProgressFromJSON,
    ProjectProgressToJSON,
} from '../models/index';

export interface ProjectGoalCreateGoalRequest {
    projectId: number;
    goalRequest: GoalRequest;
}

export interface ProjectGoalDeleteGoalRequest {
    projectId: number;
    goalId: number;
}

export interface ProjectGoalGetGoalRequest {
    projectId: number;
    goalId: number;
}

export interface ProjectGoalGetGoalsRequest {
    projectId: number;
}

export interface ProjectGoalGetProgressRequest {
    projectId: number;
}

export interface ProjectGoalUpdateGoalRequest {
    projectId: number;
    goalId: number;
    goalRequest: GoalRequest;
}

/**
 * ProjectGoalsApi - interface
 * 
 * @export
 * @interface ProjectGoalsApiInterface
 */
export interface ProjectGoalsApiInterface {
    /**
     * 
     * @summary Create goal
     * @param {number} projectId 
     * @param {GoalRequest} goalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGoalsApiInterface
     */
    projectGoalCreateGoalRaw(requestParameters: ProjectGoalCreateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectGoalDTO>>;

    /**
     * Create goal
     */
    projectGoalCreateGoal(requestParameters: ProjectGoalCreateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectGoalDTO>;

    /**
     * 
     * @summary Delete goal
     * @param {number} projectId 
     * @param {number} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGoalsApiInterface
     */
    projectGoalDeleteGoalRaw(requestParameters: ProjectGoalDeleteGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete goal
     */
    projectGoalDeleteGoal(requestParameters: ProjectGoalDeleteGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get goal
     * @param {number} projectId 
     * @param {number} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGoalsApiInterface
     */
    projectGoalGetGoalRaw(requestParameters: ProjectGoalGetGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectGoalDTO>>;

    /**
     * Get goal
     */
    projectGoalGetGoal(requestParameters: ProjectGoalGetGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectGoalDTO>;

    /**
     * 
     * @summary Get goals
     * @param {number} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGoalsApiInterface
     */
    projectGoalGetGoalsRaw(requestParameters: ProjectGoalGetGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectGoalDTO>>>;

    /**
     * Get goals
     */
    projectGoalGetGoals(requestParameters: ProjectGoalGetGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectGoalDTO>>;

    /**
     * 
     * @summary Returns the project\'s progress derived from its goals and their tasks
     * @param {number} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGoalsApiInterface
     */
    projectGoalGetProgressRaw(requestParameters: ProjectGoalGetProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectProgress>>;

    /**
     * Returns the project\'s progress derived from its goals and their tasks
     */
    projectGoalGetProgress(requestParameters: ProjectGoalGetProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectProgress>;

    /**
     * 
     * @summary Update goal
     * @param {number} projectId 
     * @param {number} goalId 
     * @param {GoalRequest} goalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGoalsApiInterface
     */
    projectGoalUpdateGoalRaw(requestParameters: ProjectGoalUpdateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectGoalDTO>>;

    /**
     * Update goal
     */
    projectGoalUpdateGoal(requestParameters: ProjectGoalUpdateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectGoalDTO>;

}

/**
 * 
 */
export class ProjectGoalsApi extends runtime.BaseAPI implements ProjectGoalsApiInterface {

    /**
     * Create goal
     */
    async projectGoalCreateGoalRaw(requestParameters: ProjectGoalCreateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectGoalDTO>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectGoalCreateGoal().'
            );
        }

        if (requestParameters['goalRequest'] == null) {
            throw new runtime.RequiredError(
                'goalRequest',
                'Required parameter "goalRequest" was null or undefined when calling projectGoalCreateGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/goals`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoalRequestToJSON(requestParameters['goalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectGoalDTOFromJSON(jsonValue));
    }

    /**
     * Create goal
     */
    async projectGoalCreateGoal(requestParameters: ProjectGoalCreateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectGoalDTO> {
        const response = await this.projectGoalCreateGoalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete goal
     */
    async projectGoalDeleteGoalRaw(requestParameters: ProjectGoalDeleteGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectGoalDeleteGoal().'
            );
        }

        if (requestParameters['goalId'] == null) {
            throw new runtime.RequiredError(
                'goalId',
                'Required parameter "goalId" was null or undefined when calling projectGoalDeleteGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/goals/{goalId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters['goalId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete goal
     */
    async projectGoalDeleteGoal(requestParameters: ProjectGoalDeleteGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectGoalDeleteGoalRaw(requestParameters, initOverrides);
    }

    /**
     * Get goal
     */
    async projectGoalGetGoalRaw(requestParameters: ProjectGoalGetGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectGoalDTO>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectGoalGetGoal().'
            );
        }

        if (requestParameters['goalId'] == null) {
            throw new runtime.RequiredError(
                'goalId',
                'Required parameter "goalId" was null or undefined when calling projectGoalGetGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/goals/{goalId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters['goalId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectGoalDTOFromJSON(jsonValue));
    }

    /**
     * Get goal
     */
    async projectGoalGetGoal(requestParameters: ProjectGoalGetGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectGoalDTO> {
        const response = await this.projectGoalGetGoalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get goals
     */
    async projectGoalGetGoalsRaw(requestParameters: ProjectGoalGetGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectGoalDTO>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectGoalGetGoals().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/goals`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectGoalDTOFromJSON));
    }

    /**
     * Get goals
     */
    async projectGoalGetGoals(requestParameters: ProjectGoalGetGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectGoalDTO>> {
        const response = await this.projectGoalGetGoalsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the project\'s progress derived from its goals and their tasks
     */
    async projectGoalGetProgressRaw(requestParameters: ProjectGoalGetProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectProgress>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectGoalGetProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/progress`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectProgressFromJSON(jsonValue));
    }

    /**
     * Returns the project\'s progress derived from its goals and their tasks
     */
    async projectGoalGetProgress(requestParameters: ProjectGoalGetProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectProgress> {
        const response = await this.projectGoalGetProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update goal
     */
    async projectGoalUpdateGoalRaw(requestParameters: ProjectGoalUpdateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectGoalDTO>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectGoalUpdateGoal().'
            );
        }

        if (requestParameters['goalId'] == null) {
            throw new runtime.RequiredError(
                'goalId',
                'Required parameter "goalId" was null or undefined when calling projectGoalUpdateGoal().'
            );
        }

        if (requestParameters['goalRequest'] == null) {
            throw new runtime.RequiredError(
                'goalRequest',
                'Required parameter "goalRequest" was null or undefined when calling projectGoalUpdateGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/goals/{goalId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters['goalId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GoalRequestToJSON(requestParameters['goalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectGoalDTOFromJSON(jsonValue));
    }

    /**
     * Update goal
     */
    async projectGoalUpdateGoal(requestParameters: ProjectGoalUpdateGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectGoalDTO> {
        const response = await this.projectGoalUpdateGoalRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
