/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QualificationLevelDTO,
  QualificationLevelRequest,
  UserDTO,
} from '../models/index';
import {
    QualificationLevelDTOFromJSON,
    QualificationLevelDTOToJSON,
    QualificationLevelRequestFromJSON,
    QualificationLevelRequestToJSON,
    UserDTOFromJSON,
    UserDTOToJSON,
} from '../models/index';

export interface QualificationLevelAssignQualificationLevelRequest {
    userId: number;
    levelId?: number;
}

export interface QualificationLevelCreateQualificationLevelRequest {
    qualificationLevelRequest: QualificationLevelRequest;
}

export interface QualificationLevelDeleteQualificationLevelRequest {
    levelId: number;
}

export interface QualificationLevelGetQualificationLevelByIdRequest {
    levelId: number;
}

export interface QualificationLevelUpdateQualificationLevelRequest {
    levelId: number;
    qualificationLevelRequest: QualificationLevelRequest;
}

/**
 * QualificationLevelsApi - interface
 * 
 * @export
 * @interface QualificationLevelsApiInterface
 */
export interface QualificationLevelsApiInterface {
    /**
     * Omit levelId to take the user off their qualification level.
     * @summary Assign a user to a qualification level
     * @param {number} userId 
     * @param {number} [levelId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QualificationLevelsApiInterface
     */
    qualificationLevelAssignQualificationLevelRaw(requestParameters: QualificationLevelAssignQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTO>>;

    /**
     * Omit levelId to take the user off their qualification level.
     * Assign a user to a qualification level
     */
    qualificationLevelAssignQualificationLevel(requestParameters: QualificationLevelAssignQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTO>;

    /**
     * 
     * @summary Create qualification level
     * @param {QualificationLevelRequest} qualificationLevelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QualificationLevelsApiInterface
     */
    qualificationLevelCreateQualificationLevelRaw(requestParameters: QualificationLevelCreateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QualificationLevelDTO>>;

    /**
     * Create qualification level
     */
    qualificationLevelCreateQualificationLevel(requestParameters: QualificationLevelCreateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QualificationLevelDTO>;

    /**
     * Refused while people are still assigned to the level.
     * @summary Delete qualification level
     * @param {number} levelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QualificationLevelsApiInterface
     */
    qualificationLevelDeleteQualificationLevelRaw(requestParameters: QualificationLevelDeleteQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Refused while people are still assigned to the level.
     * Delete qualification level
     */
    qualificationLevelDeleteQualificationLevel(requestParameters: QualificationLevelDeleteQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get all qualification levels
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QualificationLevelsApiInterface
     */
    qualificationLevelGetAllQualificationLevelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QualificationLevelDTO>>>;

    /**
     * Get all qualification levels
     */
    qualificationLevelGetAllQualificationLevels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QualificationLevelDTO>>;

    /**
     * 
     * @summary Get qualification level by id
     * @param {number} levelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QualificationLevelsApiInterface
     */
    qualificationLevelGetQualificationLevelByIdRaw(requestParameters: QualificationLevelGetQualificationLevelByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QualificationLevelDTO>>;

    /**
     * Get qualification level by id
     */
    qualificationLevelGetQualificationLevelById(requestParameters: QualificationLevelGetQualificationLevelByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QualificationLevelDTO>;

    /**
     * Replaces the level. Omitting the three cost fields clears its cost rate.
     * @summary Update qualification level
     * @param {number} levelId 
     * @param {QualificationLevelRequest} qualificationLevelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QualificationLevelsApiInterface
     */
    qualificationLevelUpdateQualificationLevelRaw(requestParameters: QualificationLevelUpdateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QualificationLevelDTO>>;

    /**
     * Replaces the level. Omitting the three cost fields clears its cost rate.
     * Update qualification level
     */
    qualificationLevelUpdateQualificationLevel(requestParameters: QualificationLevelUpdateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QualificationLevelDTO>;

}

/**
 * 
 */
export class QualificationLevelsApi extends runtime.BaseAPI implements QualificationLevelsApiInterface {

    /**
     * Omit levelId to take the user off their qualification level.
     * Assign a user to a qualification level
     */
    async qualificationLevelAssignQualificationLevelRaw(requestParameters: QualificationLevelAssignQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTO>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling qualificationLevelAssignQualificationLevel().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['levelId'] != null) {
            queryParameters['levelId'] = requestParameters['levelId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/users/{userId}/qualification-level`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDTOFromJSON(jsonValue));
    }

    /**
     * Omit levelId to take the user off their qualification level.
     * Assign a user to a qualification level
     */
    async qualificationLevelAssignQualificationLevel(requestParameters: QualificationLevelAssignQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTO> {
        const response = await this.qualificationLevelAssignQualificationLevelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create qualification level
     */
    async qualificationLevelCreateQualificationLevelRaw(requestParameters: QualificationLevelCreateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QualificationLevelDTO>> {
        if (requestParameters['qualificationLevelRequest'] == null) {
            throw new runtime.RequiredError(
                'qualificationLevelRequest',
                'Required parameter "qualificationLevelRequest" was null or undefined when calling qualificationLevelCreateQualificationLevel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/qualification-levels`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QualificationLevelRequestToJSON(requestParameters['qualificationLevelRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QualificationLevelDTOFromJSON(jsonValue));
    }

    /**
     * Create qualification level
     */
    async qualificationLevelCreateQualificationLevel(requestParameters: QualificationLevelCreateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QualificationLevelDTO> {
        const response = await this.qualificationLevelCreateQualificationLevelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refused while people are still assigned to the level.
     * Delete qualification level
     */
    async qualificationLevelDeleteQualificationLevelRaw(requestParameters: QualificationLevelDeleteQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling qualificationLevelDeleteQualificationLevel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/qualification-levels/{levelId}`.replace(`{${"levelId"}}`, encodeURIComponent(String(requestParameters['levelId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Refused while people are still assigned to the level.
     * Delete qualification level
     */
    async qualificationLevelDeleteQualificationLevel(requestParameters: QualificationLevelDeleteQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.qualificationLevelDeleteQualificationLevelRaw(requestParameters, initOverrides);
    }

    /**
     * Get all qualification levels
     */
    async qualificationLevelGetAllQualificationLevelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QualificationLevelDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/qualification-levels`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QualificationLevelDTOFromJSON));
    }

    /**
     * Get all qualification levels
     */
    async qualificationLevelGetAllQualificationLevels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QualificationLevelDTO>> {
        const response = await this.qualificationLevelGetAllQualificationLevelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get qualification level by id
     */
    async qualificationLevelGetQualificationLevelByIdRaw(requestParameters: QualificationLevelGetQualificationLevelByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QualificationLevelDTO>> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling qualificationLevelGetQualificationLevelById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/qualification-levels/{levelId}`.replace(`{${"levelId"}}`, encodeURIComponent(String(requestParameters['levelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QualificationLevelDTOFromJSON(jsonValue));
    }

    /**
     * Get qualification level by id
     */
    async qualificationLevelGetQualificationLevelById(requestParameters: QualificationLevelGetQualificationLevelByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QualificationLevelDTO> {
        const response = await this.qualificationLevelGetQualificationLevelByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces the level. Omitting the three cost fields clears its cost rate.
     * Update qualification level
     */
    async qualificationLevelUpdateQualificationLevelRaw(requestParameters: QualificationLevelUpdateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QualificationLevelDTO>> {
        if (requestParameters['levelId'] == null) {
            throw new runtime.RequiredError(
                'levelId',
                'Required parameter "levelId" was null or undefined when calling qualificationLevelUpdateQualificationLevel().'
            );
        }

        if (requestParameters['qualificationLevelRequest'] == null) {
            throw new runtime.RequiredError(
                'qualificationLevelRequest',
                'Required parameter "qualificationLevelRequest" was null or undefined when calling qualificationLevelUpdateQualificationLevel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/qualification-levels/{levelId}`.replace(`{${"levelId"}}`, encodeURIComponent(String(requestParameters['levelId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: QualificationLevelRequestToJSON(requestParameters['qualificationLevelRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QualificationLevelDTOFromJSON(jsonValue));
    }

    /**
     * Replaces the level. Omitting the three cost fields clears its cost rate.
     * Update qualification level
     */
    async qualificationLevelUpdateQualificationLevel(requestParameters: QualificationLevelUpdateQualificationLevelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QualificationLevelDTO> {
        const response = await this.qualificationLevelUpdateQualificationLevelRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
