/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TaskScheduleDTO,
  TaskScheduleRequest,
} from '../models/index';
import {
    TaskScheduleDTOFromJSON,
    TaskScheduleDTOToJSON,
    TaskScheduleRequestFromJSON,
    TaskScheduleRequestToJSON,
} from '../models/index';

export interface TaskScheduleCreateScheduleRequest {
    projectId: number;
    taskScheduleRequest: TaskScheduleRequest;
}

export interface TaskScheduleDeleteScheduleRequest {
    id: number;
}

export interface TaskScheduleGetScheduleRequest {
    id: number;
}

export interface TaskScheduleGetSchedulesRequest {
    projectId: number;
}

export interface TaskScheduleUpdateScheduleRequest {
    id: number;
    taskScheduleRequest: TaskScheduleRequest;
}

/**
 * TaskSchedulesApi - interface
 * 
 * @export
 * @interface TaskSchedulesApiInterface
 */
export interface TaskSchedulesApiInterface {
    /**
     * 
     * @summary Creates a recurring task schedule on a project
     * @param {number} projectId 
     * @param {TaskScheduleRequest} taskScheduleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSchedulesApiInterface
     */
    taskScheduleCreateScheduleRaw(requestParameters: TaskScheduleCreateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskScheduleDTO>>;

    /**
     * Creates a recurring task schedule on a project
     */
    taskScheduleCreateSchedule(requestParameters: TaskScheduleCreateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskScheduleDTO>;

    /**
     * 
     * @summary Deletes a schedule
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSchedulesApiInterface
     */
    taskScheduleDeleteScheduleRaw(requestParameters: TaskScheduleDeleteScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a schedule
     */
    taskScheduleDeleteSchedule(requestParameters: TaskScheduleDeleteScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Returns a single schedule by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSchedulesApiInterface
     */
    taskScheduleGetScheduleRaw(requestParameters: TaskScheduleGetScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskScheduleDTO>>;

    /**
     * Returns a single schedule by id
     */
    taskScheduleGetSchedule(requestParameters: TaskScheduleGetScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskScheduleDTO>;

    /**
     * 
     * @summary Lists all schedules of a project (enabled or not)
     * @param {number} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSchedulesApiInterface
     */
    taskScheduleGetSchedulesRaw(requestParameters: TaskScheduleGetSchedulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskScheduleDTO>>>;

    /**
     * Lists all schedules of a project (enabled or not)
     */
    taskScheduleGetSchedules(requestParameters: TaskScheduleGetSchedulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskScheduleDTO>>;

    /**
     * 
     * @summary Partially updates a schedule (only the fields present in the body are changed)
     * @param {number} id 
     * @param {TaskScheduleRequest} taskScheduleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSchedulesApiInterface
     */
    taskScheduleUpdateScheduleRaw(requestParameters: TaskScheduleUpdateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskScheduleDTO>>;

    /**
     * Partially updates a schedule (only the fields present in the body are changed)
     */
    taskScheduleUpdateSchedule(requestParameters: TaskScheduleUpdateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskScheduleDTO>;

}

/**
 * 
 */
export class TaskSchedulesApi extends runtime.BaseAPI implements TaskSchedulesApiInterface {

    /**
     * Creates a recurring task schedule on a project
     */
    async taskScheduleCreateScheduleRaw(requestParameters: TaskScheduleCreateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskScheduleDTO>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling taskScheduleCreateSchedule().'
            );
        }

        if (requestParameters['taskScheduleRequest'] == null) {
            throw new runtime.RequiredError(
                'taskScheduleRequest',
                'Required parameter "taskScheduleRequest" was null or undefined when calling taskScheduleCreateSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/task-schedules`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskScheduleRequestToJSON(requestParameters['taskScheduleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskScheduleDTOFromJSON(jsonValue));
    }

    /**
     * Creates a recurring task schedule on a project
     */
    async taskScheduleCreateSchedule(requestParameters: TaskScheduleCreateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskScheduleDTO> {
        const response = await this.taskScheduleCreateScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a schedule
     */
    async taskScheduleDeleteScheduleRaw(requestParameters: TaskScheduleDeleteScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskScheduleDeleteSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/task-schedules/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a schedule
     */
    async taskScheduleDeleteSchedule(requestParameters: TaskScheduleDeleteScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taskScheduleDeleteScheduleRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a single schedule by id
     */
    async taskScheduleGetScheduleRaw(requestParameters: TaskScheduleGetScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskScheduleDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskScheduleGetSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/task-schedules/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskScheduleDTOFromJSON(jsonValue));
    }

    /**
     * Returns a single schedule by id
     */
    async taskScheduleGetSchedule(requestParameters: TaskScheduleGetScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskScheduleDTO> {
        const response = await this.taskScheduleGetScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all schedules of a project (enabled or not)
     */
    async taskScheduleGetSchedulesRaw(requestParameters: TaskScheduleGetSchedulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskScheduleDTO>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling taskScheduleGetSchedules().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/task-schedules`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskScheduleDTOFromJSON));
    }

    /**
     * Lists all schedules of a project (enabled or not)
     */
    async taskScheduleGetSchedules(requestParameters: TaskScheduleGetSchedulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskScheduleDTO>> {
        const response = await this.taskScheduleGetSchedulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Partially updates a schedule (only the fields present in the body are changed)
     */
    async taskScheduleUpdateScheduleRaw(requestParameters: TaskScheduleUpdateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskScheduleDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskScheduleUpdateSchedule().'
            );
        }

        if (requestParameters['taskScheduleRequest'] == null) {
            throw new runtime.RequiredError(
                'taskScheduleRequest',
                'Required parameter "taskScheduleRequest" was null or undefined when calling taskScheduleUpdateSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/task-schedules/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TaskScheduleRequestToJSON(requestParameters['taskScheduleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskScheduleDTOFromJSON(jsonValue));
    }

    /**
     * Partially updates a schedule (only the fields present in the body are changed)
     */
    async taskScheduleUpdateSchedule(requestParameters: TaskScheduleUpdateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskScheduleDTO> {
        const response = await this.taskScheduleUpdateScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
