/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StopAtRequest,
  TaskDTO,
  TaskRequest,
  TaskStatusRequest,
  TrackingSummary,
  WorkSession,
  WorkSessionRequest,
} from '../models/index';
import {
    StopAtRequestFromJSON,
    StopAtRequestToJSON,
    TaskDTOFromJSON,
    TaskDTOToJSON,
    TaskRequestFromJSON,
    TaskRequestToJSON,
    TaskStatusRequestFromJSON,
    TaskStatusRequestToJSON,
    TrackingSummaryFromJSON,
    TrackingSummaryToJSON,
    WorkSessionFromJSON,
    WorkSessionToJSON,
    WorkSessionRequestFromJSON,
    WorkSessionRequestToJSON,
} from '../models/index';

export interface TaskAddTrackingSessionRequest {
    id: number;
    workSessionRequest: WorkSessionRequest;
}

export interface TaskAssignGoalRequest {
    id: number;
    goalId: number;
}

export interface TaskAssignTaskRequest {
    id: number;
    actorId: number;
}

export interface TaskChangeStatusRequest {
    id: number;
    taskStatusRequest: TaskStatusRequest;
}

export interface TaskCreateTaskRequest {
    projectId: number;
    taskRequest: TaskRequest;
}

export interface TaskDeleteTaskRequest {
    id: number;
}

export interface TaskDeleteTrackingSessionRequest {
    id: number;
    sessionId: number;
}

export interface TaskGetTaskRequest {
    id: number;
}

export interface TaskGetTrackingRequest {
    id: number;
}

export interface TaskGetTrackingSessionsRequest {
    id: number;
}

export interface TaskStartTrackingRequest {
    id: number;
}

export interface TaskStopTrackingRequest {
    id: number;
}

export interface TaskStopTrackingAtRequest {
    id: number;
    stopAtRequest: StopAtRequest;
}

export interface TaskToggleTrackingRequest {
    id: number;
}

export interface TaskUnassignGoalRequest {
    id: number;
}

export interface TaskUnassignTaskRequest {
    id: number;
}

export interface TaskUpdateTaskRequest {
    id: number;
    taskRequest: TaskRequest;
}

export interface TaskUpdateTrackingSessionRequest {
    id: number;
    sessionId: number;
    workSessionRequest: WorkSessionRequest;
}

/**
 * TasksApi - interface
 * 
 * @export
 * @interface TasksApiInterface
 */
export interface TasksApiInterface {
    /**
     * 
     * @summary Books a work session by hand that was never clocked
     * @param {number} id 
     * @param {WorkSessionRequest} workSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskAddTrackingSessionRaw(requestParameters: TaskAddTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkSession>>;

    /**
     * Books a work session by hand that was never clocked
     */
    taskAddTrackingSession(requestParameters: TaskAddTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkSession>;

    /**
     * 
     * @summary Assign goal
     * @param {number} id 
     * @param {number} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskAssignGoalRaw(requestParameters: TaskAssignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Assign goal
     */
    taskAssignGoal(requestParameters: TaskAssignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Assign task
     * @param {number} id 
     * @param {number} actorId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskAssignTaskRaw(requestParameters: TaskAssignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Assign task
     */
    taskAssignTask(requestParameters: TaskAssignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Change status
     * @param {number} id 
     * @param {TaskStatusRequest} taskStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskChangeStatusRaw(requestParameters: TaskChangeStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Change status
     */
    taskChangeStatus(requestParameters: TaskChangeStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Creates a task on the given project\'s blackboard
     * @param {number} projectId 
     * @param {TaskRequest} taskRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskCreateTaskRaw(requestParameters: TaskCreateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Creates a task on the given project\'s blackboard
     */
    taskCreateTask(requestParameters: TaskCreateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Delete task
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskDeleteTaskRaw(requestParameters: TaskDeleteTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete task
     */
    taskDeleteTask(requestParameters: TaskDeleteTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Removes a completed work session
     * @param {number} id 
     * @param {number} sessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskDeleteTrackingSessionRaw(requestParameters: TaskDeleteTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes a completed work session
     */
    taskDeleteTrackingSession(requestParameters: TaskDeleteTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get task
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskGetTaskRaw(requestParameters: TaskGetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Get task
     */
    taskGetTask(requestParameters: TaskGetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Returns the total time tracked on the task (completed spans plus the running one, live)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskGetTrackingRaw(requestParameters: TaskGetTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrackingSummary>>;

    /**
     * Returns the total time tracked on the task (completed spans plus the running one, live)
     */
    taskGetTracking(requestParameters: TaskGetTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrackingSummary>;

    /**
     * 
     * @summary Returns the individual tracked work sessions of the task (completed spans plus the running one)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskGetTrackingSessionsRaw(requestParameters: TaskGetTrackingSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkSession>>>;

    /**
     * Returns the individual tracked work sessions of the task (completed spans plus the running one)
     */
    taskGetTrackingSessions(requestParameters: TaskGetTrackingSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkSession>>;

    /**
     * 
     * @summary Start tracking
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskStartTrackingRaw(requestParameters: TaskStartTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Start tracking
     */
    taskStartTracking(requestParameters: TaskStartTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Stop tracking
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskStopTrackingRaw(requestParameters: TaskStopTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Stop tracking
     */
    taskStopTracking(requestParameters: TaskStopTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Stops the running work session at an earlier point in time
     * @param {number} id 
     * @param {StopAtRequest} stopAtRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskStopTrackingAtRaw(requestParameters: TaskStopTrackingAtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Stops the running work session at an earlier point in time
     */
    taskStopTrackingAt(requestParameters: TaskStopTrackingAtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Toggle tracking
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskToggleTrackingRaw(requestParameters: TaskToggleTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Toggle tracking
     */
    taskToggleTracking(requestParameters: TaskToggleTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Unassign goal
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskUnassignGoalRaw(requestParameters: TaskUnassignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Unassign goal
     */
    taskUnassignGoal(requestParameters: TaskUnassignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Unassign task
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskUnassignTaskRaw(requestParameters: TaskUnassignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Unassign task
     */
    taskUnassignTask(requestParameters: TaskUnassignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Update task
     * @param {number} id 
     * @param {TaskRequest} taskRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskUpdateTaskRaw(requestParameters: TaskUpdateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>>;

    /**
     * Update task
     */
    taskUpdateTask(requestParameters: TaskUpdateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO>;

    /**
     * 
     * @summary Corrects the start and end of a completed work session
     * @param {number} id 
     * @param {number} sessionId 
     * @param {WorkSessionRequest} workSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApiInterface
     */
    taskUpdateTrackingSessionRaw(requestParameters: TaskUpdateTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkSession>>;

    /**
     * Corrects the start and end of a completed work session
     */
    taskUpdateTrackingSession(requestParameters: TaskUpdateTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkSession>;

}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI implements TasksApiInterface {

    /**
     * Books a work session by hand that was never clocked
     */
    async taskAddTrackingSessionRaw(requestParameters: TaskAddTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkSession>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskAddTrackingSession().'
            );
        }

        if (requestParameters['workSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'workSessionRequest',
                'Required parameter "workSessionRequest" was null or undefined when calling taskAddTrackingSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/sessions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkSessionRequestToJSON(requestParameters['workSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkSessionFromJSON(jsonValue));
    }

    /**
     * Books a work session by hand that was never clocked
     */
    async taskAddTrackingSession(requestParameters: TaskAddTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkSession> {
        const response = await this.taskAddTrackingSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Assign goal
     */
    async taskAssignGoalRaw(requestParameters: TaskAssignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskAssignGoal().'
            );
        }

        if (requestParameters['goalId'] == null) {
            throw new runtime.RequiredError(
                'goalId',
                'Required parameter "goalId" was null or undefined when calling taskAssignGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/goal/{goalId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters['goalId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Assign goal
     */
    async taskAssignGoal(requestParameters: TaskAssignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskAssignGoalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Assign task
     */
    async taskAssignTaskRaw(requestParameters: TaskAssignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskAssignTask().'
            );
        }

        if (requestParameters['actorId'] == null) {
            throw new runtime.RequiredError(
                'actorId',
                'Required parameter "actorId" was null or undefined when calling taskAssignTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/assignee/{actorId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"actorId"}}`, encodeURIComponent(String(requestParameters['actorId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Assign task
     */
    async taskAssignTask(requestParameters: TaskAssignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskAssignTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change status
     */
    async taskChangeStatusRaw(requestParameters: TaskChangeStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskChangeStatus().'
            );
        }

        if (requestParameters['taskStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'taskStatusRequest',
                'Required parameter "taskStatusRequest" was null or undefined when calling taskChangeStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/status`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TaskStatusRequestToJSON(requestParameters['taskStatusRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Change status
     */
    async taskChangeStatus(requestParameters: TaskChangeStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskChangeStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a task on the given project\'s blackboard
     */
    async taskCreateTaskRaw(requestParameters: TaskCreateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling taskCreateTask().'
            );
        }

        if (requestParameters['taskRequest'] == null) {
            throw new runtime.RequiredError(
                'taskRequest',
                'Required parameter "taskRequest" was null or undefined when calling taskCreateTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/projects/{projectId}/tasks`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskRequestToJSON(requestParameters['taskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Creates a task on the given project\'s blackboard
     */
    async taskCreateTask(requestParameters: TaskCreateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskCreateTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete task
     */
    async taskDeleteTaskRaw(requestParameters: TaskDeleteTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskDeleteTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete task
     */
    async taskDeleteTask(requestParameters: TaskDeleteTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taskDeleteTaskRaw(requestParameters, initOverrides);
    }

    /**
     * Removes a completed work session
     */
    async taskDeleteTrackingSessionRaw(requestParameters: TaskDeleteTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskDeleteTrackingSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling taskDeleteTrackingSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/sessions/{sessionId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a completed work session
     */
    async taskDeleteTrackingSession(requestParameters: TaskDeleteTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taskDeleteTrackingSessionRaw(requestParameters, initOverrides);
    }

    /**
     * Get task
     */
    async taskGetTaskRaw(requestParameters: TaskGetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskGetTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Get task
     */
    async taskGetTask(requestParameters: TaskGetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskGetTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the total time tracked on the task (completed spans plus the running one, live)
     */
    async taskGetTrackingRaw(requestParameters: TaskGetTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrackingSummary>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskGetTracking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrackingSummaryFromJSON(jsonValue));
    }

    /**
     * Returns the total time tracked on the task (completed spans plus the running one, live)
     */
    async taskGetTracking(requestParameters: TaskGetTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrackingSummary> {
        const response = await this.taskGetTrackingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the individual tracked work sessions of the task (completed spans plus the running one)
     */
    async taskGetTrackingSessionsRaw(requestParameters: TaskGetTrackingSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkSession>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskGetTrackingSessions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/sessions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkSessionFromJSON));
    }

    /**
     * Returns the individual tracked work sessions of the task (completed spans plus the running one)
     */
    async taskGetTrackingSessions(requestParameters: TaskGetTrackingSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkSession>> {
        const response = await this.taskGetTrackingSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start tracking
     */
    async taskStartTrackingRaw(requestParameters: TaskStartTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskStartTracking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/start`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Start tracking
     */
    async taskStartTracking(requestParameters: TaskStartTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskStartTrackingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop tracking
     */
    async taskStopTrackingRaw(requestParameters: TaskStopTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskStopTracking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/stop`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Stop tracking
     */
    async taskStopTracking(requestParameters: TaskStopTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskStopTrackingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stops the running work session at an earlier point in time
     */
    async taskStopTrackingAtRaw(requestParameters: TaskStopTrackingAtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskStopTrackingAt().'
            );
        }

        if (requestParameters['stopAtRequest'] == null) {
            throw new runtime.RequiredError(
                'stopAtRequest',
                'Required parameter "stopAtRequest" was null or undefined when calling taskStopTrackingAt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/stop-at`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StopAtRequestToJSON(requestParameters['stopAtRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Stops the running work session at an earlier point in time
     */
    async taskStopTrackingAt(requestParameters: TaskStopTrackingAtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskStopTrackingAtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Toggle tracking
     */
    async taskToggleTrackingRaw(requestParameters: TaskToggleTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskToggleTracking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/toggle`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Toggle tracking
     */
    async taskToggleTracking(requestParameters: TaskToggleTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskToggleTrackingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unassign goal
     */
    async taskUnassignGoalRaw(requestParameters: TaskUnassignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskUnassignGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/goal`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Unassign goal
     */
    async taskUnassignGoal(requestParameters: TaskUnassignGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskUnassignGoalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unassign task
     */
    async taskUnassignTaskRaw(requestParameters: TaskUnassignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskUnassignTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/assignee`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Unassign task
     */
    async taskUnassignTask(requestParameters: TaskUnassignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskUnassignTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update task
     */
    async taskUpdateTaskRaw(requestParameters: TaskUpdateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskUpdateTask().'
            );
        }

        if (requestParameters['taskRequest'] == null) {
            throw new runtime.RequiredError(
                'taskRequest',
                'Required parameter "taskRequest" was null or undefined when calling taskUpdateTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TaskRequestToJSON(requestParameters['taskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskDTOFromJSON(jsonValue));
    }

    /**
     * Update task
     */
    async taskUpdateTask(requestParameters: TaskUpdateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskDTO> {
        const response = await this.taskUpdateTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Corrects the start and end of a completed work session
     */
    async taskUpdateTrackingSessionRaw(requestParameters: TaskUpdateTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkSession>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskUpdateTrackingSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling taskUpdateTrackingSession().'
            );
        }

        if (requestParameters['workSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'workSessionRequest',
                'Required parameter "workSessionRequest" was null or undefined when calling taskUpdateTrackingSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tasks/{id}/tracking/sessions/{sessionId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WorkSessionRequestToJSON(requestParameters['workSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkSessionFromJSON(jsonValue));
    }

    /**
     * Corrects the start and end of a completed work session
     */
    async taskUpdateTrackingSession(requestParameters: TaskUpdateTrackingSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkSession> {
        const response = await this.taskUpdateTrackingSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
