/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TelemetryRuleDTO,
  TelemetryRuleRequest,
} from '../models/index';
import {
    TelemetryRuleDTOFromJSON,
    TelemetryRuleDTOToJSON,
    TelemetryRuleRequestFromJSON,
    TelemetryRuleRequestToJSON,
} from '../models/index';

export interface TelemetryRuleCreateRuleRequest {
    resourceId: number;
    telemetryRuleRequest: TelemetryRuleRequest;
}

export interface TelemetryRuleDeleteRuleRequest {
    id: number;
}

export interface TelemetryRuleGetRuleRequest {
    id: number;
}

export interface TelemetryRuleGetRulesRequest {
    resourceId: number;
}

export interface TelemetryRuleUpdateRuleRequest {
    id: number;
    telemetryRuleRequest: TelemetryRuleRequest;
}

/**
 * TelemetryRulesApi - interface
 * 
 * @export
 * @interface TelemetryRulesApiInterface
 */
export interface TelemetryRulesApiInterface {
    /**
     * 
     * @summary Creates a monitoring rule on a resource
     * @param {number} resourceId 
     * @param {TelemetryRuleRequest} telemetryRuleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TelemetryRulesApiInterface
     */
    telemetryRuleCreateRuleRaw(requestParameters: TelemetryRuleCreateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetryRuleDTO>>;

    /**
     * Creates a monitoring rule on a resource
     */
    telemetryRuleCreateRule(requestParameters: TelemetryRuleCreateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetryRuleDTO>;

    /**
     * 
     * @summary Deletes a rule
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TelemetryRulesApiInterface
     */
    telemetryRuleDeleteRuleRaw(requestParameters: TelemetryRuleDeleteRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a rule
     */
    telemetryRuleDeleteRule(requestParameters: TelemetryRuleDeleteRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Returns a single rule by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TelemetryRulesApiInterface
     */
    telemetryRuleGetRuleRaw(requestParameters: TelemetryRuleGetRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetryRuleDTO>>;

    /**
     * Returns a single rule by id
     */
    telemetryRuleGetRule(requestParameters: TelemetryRuleGetRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetryRuleDTO>;

    /**
     * 
     * @summary Lists all monitoring rules of a resource (any data point, enabled or not)
     * @param {number} resourceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TelemetryRulesApiInterface
     */
    telemetryRuleGetRulesRaw(requestParameters: TelemetryRuleGetRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TelemetryRuleDTO>>>;

    /**
     * Lists all monitoring rules of a resource (any data point, enabled or not)
     */
    telemetryRuleGetRules(requestParameters: TelemetryRuleGetRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TelemetryRuleDTO>>;

    /**
     * 
     * @summary Partially updates a rule (only the fields present in the body are changed)
     * @param {number} id 
     * @param {TelemetryRuleRequest} telemetryRuleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TelemetryRulesApiInterface
     */
    telemetryRuleUpdateRuleRaw(requestParameters: TelemetryRuleUpdateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetryRuleDTO>>;

    /**
     * Partially updates a rule (only the fields present in the body are changed)
     */
    telemetryRuleUpdateRule(requestParameters: TelemetryRuleUpdateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetryRuleDTO>;

}

/**
 * 
 */
export class TelemetryRulesApi extends runtime.BaseAPI implements TelemetryRulesApiInterface {

    /**
     * Creates a monitoring rule on a resource
     */
    async telemetryRuleCreateRuleRaw(requestParameters: TelemetryRuleCreateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetryRuleDTO>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling telemetryRuleCreateRule().'
            );
        }

        if (requestParameters['telemetryRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'telemetryRuleRequest',
                'Required parameter "telemetryRuleRequest" was null or undefined when calling telemetryRuleCreateRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/resources/{resourceId}/telemetry-rules`.replace(`{${"resourceId"}}`, encodeURIComponent(String(requestParameters['resourceId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TelemetryRuleRequestToJSON(requestParameters['telemetryRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TelemetryRuleDTOFromJSON(jsonValue));
    }

    /**
     * Creates a monitoring rule on a resource
     */
    async telemetryRuleCreateRule(requestParameters: TelemetryRuleCreateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetryRuleDTO> {
        const response = await this.telemetryRuleCreateRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a rule
     */
    async telemetryRuleDeleteRuleRaw(requestParameters: TelemetryRuleDeleteRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling telemetryRuleDeleteRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/telemetry-rules/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a rule
     */
    async telemetryRuleDeleteRule(requestParameters: TelemetryRuleDeleteRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.telemetryRuleDeleteRuleRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a single rule by id
     */
    async telemetryRuleGetRuleRaw(requestParameters: TelemetryRuleGetRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetryRuleDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling telemetryRuleGetRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/telemetry-rules/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TelemetryRuleDTOFromJSON(jsonValue));
    }

    /**
     * Returns a single rule by id
     */
    async telemetryRuleGetRule(requestParameters: TelemetryRuleGetRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetryRuleDTO> {
        const response = await this.telemetryRuleGetRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all monitoring rules of a resource (any data point, enabled or not)
     */
    async telemetryRuleGetRulesRaw(requestParameters: TelemetryRuleGetRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TelemetryRuleDTO>>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling telemetryRuleGetRules().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/resources/{resourceId}/telemetry-rules`.replace(`{${"resourceId"}}`, encodeURIComponent(String(requestParameters['resourceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TelemetryRuleDTOFromJSON));
    }

    /**
     * Lists all monitoring rules of a resource (any data point, enabled or not)
     */
    async telemetryRuleGetRules(requestParameters: TelemetryRuleGetRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TelemetryRuleDTO>> {
        const response = await this.telemetryRuleGetRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Partially updates a rule (only the fields present in the body are changed)
     */
    async telemetryRuleUpdateRuleRaw(requestParameters: TelemetryRuleUpdateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetryRuleDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling telemetryRuleUpdateRule().'
            );
        }

        if (requestParameters['telemetryRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'telemetryRuleRequest',
                'Required parameter "telemetryRuleRequest" was null or undefined when calling telemetryRuleUpdateRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/telemetry-rules/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TelemetryRuleRequestToJSON(requestParameters['telemetryRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TelemetryRuleDTOFromJSON(jsonValue));
    }

    /**
     * Partially updates a rule (only the fields present in the body are changed)
     */
    async telemetryRuleUpdateRule(requestParameters: TelemetryRuleUpdateRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetryRuleDTO> {
        const response = await this.telemetryRuleUpdateRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
