/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressRequest
 */
export interface AddressRequest {
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    housenumber?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    floor?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    zipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    fax?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    mobile?: string;
}

/**
 * Check if a given object implements the AddressRequest interface.
 */
export function instanceOfAddressRequest(value: object): value is AddressRequest {
    return true;
}

export function AddressRequestFromJSON(json: any): AddressRequest {
    return AddressRequestFromJSONTyped(json, false);
}

export function AddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'] == null ? undefined : json['street'],
        'housenumber': json['housenumber'] == null ? undefined : json['housenumber'],
        'floor': json['floor'] == null ? undefined : json['floor'],
        'zipCode': json['zipCode'] == null ? undefined : json['zipCode'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'fax': json['fax'] == null ? undefined : json['fax'],
        'mobile': json['mobile'] == null ? undefined : json['mobile'],
    };
}

export function AddressRequestToJSON(json: any): AddressRequest {
    return AddressRequestToJSONTyped(json, false);
}

export function AddressRequestToJSONTyped(value?: AddressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'housenumber': value['housenumber'],
        'floor': value['floor'],
        'zipCode': value['zipCode'],
        'city': value['city'],
        'country': value['country'],
        'phone': value['phone'],
        'fax': value['fax'],
        'mobile': value['mobile'],
    };
}

