/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelProcessInstanceRequest
 */
export interface CancelProcessInstanceRequest {
    /**
     * 
     * @type {string}
     * @memberof CancelProcessInstanceRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the CancelProcessInstanceRequest interface.
 */
export function instanceOfCancelProcessInstanceRequest(value: object): value is CancelProcessInstanceRequest {
    return true;
}

export function CancelProcessInstanceRequestFromJSON(json: any): CancelProcessInstanceRequest {
    return CancelProcessInstanceRequestFromJSONTyped(json, false);
}

export function CancelProcessInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelProcessInstanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function CancelProcessInstanceRequestToJSON(json: any): CancelProcessInstanceRequest {
    return CancelProcessInstanceRequestToJSONTyped(json, false);
}

export function CancelProcessInstanceRequestToJSONTyped(value?: CancelProcessInstanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

