/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressDTO } from './AddressDTO';
import {
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
    AddressDTOToJSONTyped,
} from './AddressDTO';

/**
 * 
 * @export
 * @interface CompanyDTO
 */
export interface CompanyDTO {
    /**
     * 
     * @type {number}
     * @memberof CompanyDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDTO
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDTO
     */
    vatNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDTO
     */
    taxId?: string;
    /**
     * 
     * @type {AddressDTO}
     * @memberof CompanyDTO
     */
    mainAddress?: AddressDTO;
}

/**
 * Check if a given object implements the CompanyDTO interface.
 */
export function instanceOfCompanyDTO(value: object): value is CompanyDTO {
    return true;
}

export function CompanyDTOFromJSON(json: any): CompanyDTO {
    return CompanyDTOFromJSONTyped(json, false);
}

export function CompanyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'url': json['url'] == null ? undefined : json['url'],
        'vatNumber': json['vatNumber'] == null ? undefined : json['vatNumber'],
        'taxId': json['taxId'] == null ? undefined : json['taxId'],
        'mainAddress': json['mainAddress'] == null ? undefined : AddressDTOFromJSON(json['mainAddress']),
    };
}

export function CompanyDTOToJSON(json: any): CompanyDTO {
    return CompanyDTOToJSONTyped(json, false);
}

export function CompanyDTOToJSONTyped(value?: CompanyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'url': value['url'],
        'vatNumber': value['vatNumber'],
        'taxId': value['taxId'],
        'mainAddress': AddressDTOToJSON(value['mainAddress']),
    };
}

