/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressRequest } from './AddressRequest';
import {
    AddressRequestFromJSON,
    AddressRequestFromJSONTyped,
    AddressRequestToJSON,
    AddressRequestToJSONTyped,
} from './AddressRequest';

/**
 * 
 * @export
 * @interface CompanyRequest
 */
export interface CompanyRequest {
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    vatNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyRequest
     */
    taxId?: string;
    /**
     * 
     * @type {AddressRequest}
     * @memberof CompanyRequest
     */
    mainAddress?: AddressRequest;
}

/**
 * Check if a given object implements the CompanyRequest interface.
 */
export function instanceOfCompanyRequest(value: object): value is CompanyRequest {
    return true;
}

export function CompanyRequestFromJSON(json: any): CompanyRequest {
    return CompanyRequestFromJSONTyped(json, false);
}

export function CompanyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'url': json['url'] == null ? undefined : json['url'],
        'vatNumber': json['vatNumber'] == null ? undefined : json['vatNumber'],
        'taxId': json['taxId'] == null ? undefined : json['taxId'],
        'mainAddress': json['mainAddress'] == null ? undefined : AddressRequestFromJSON(json['mainAddress']),
    };
}

export function CompanyRequestToJSON(json: any): CompanyRequest {
    return CompanyRequestToJSONTyped(json, false);
}

export function CompanyRequestToJSONTyped(value?: CompanyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'url': value['url'],
        'vatNumber': value['vatNumber'],
        'taxId': value['taxId'],
        'mainAddress': AddressRequestToJSON(value['mainAddress']),
    };
}

