/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Correction
 */
export interface Correction {
    /**
     * 
     * @type {string}
     * @memberof Correction
     */
    kind?: CorrectionKindEnum;
    /**
     * 
     * @type {number}
     * @memberof Correction
     */
    correctedById?: number;
    /**
     * 
     * @type {string}
     * @memberof Correction
     */
    correctedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Correction
     */
    correctedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Correction
     */
    reason?: string;
    /**
     * 
     * @type {Date}
     * @memberof Correction
     */
    originalFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Correction
     */
    originalUntil?: Date;
}


/**
 * @export
 */
export const CorrectionKindEnum = {
    Corrected: 'CORRECTED',
    BackdatedStop: 'BACKDATED_STOP',
    ManualEntry: 'MANUAL_ENTRY'
} as const;
export type CorrectionKindEnum = typeof CorrectionKindEnum[keyof typeof CorrectionKindEnum];


/**
 * Check if a given object implements the Correction interface.
 */
export function instanceOfCorrection(value: object): value is Correction {
    return true;
}

export function CorrectionFromJSON(json: any): Correction {
    return CorrectionFromJSONTyped(json, false);
}

export function CorrectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Correction {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'correctedById': json['correctedById'] == null ? undefined : json['correctedById'],
        'correctedBy': json['correctedBy'] == null ? undefined : json['correctedBy'],
        'correctedAt': json['correctedAt'] == null ? undefined : (new Date(json['correctedAt'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'originalFrom': json['originalFrom'] == null ? undefined : (new Date(json['originalFrom'])),
        'originalUntil': json['originalUntil'] == null ? undefined : (new Date(json['originalUntil'])),
    };
}

export function CorrectionToJSON(json: any): Correction {
    return CorrectionToJSONTyped(json, false);
}

export function CorrectionToJSONTyped(value?: Correction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'correctedById': value['correctedById'],
        'correctedBy': value['correctedBy'],
        'correctedAt': value['correctedAt'] == null ? undefined : ((value['correctedAt']).toISOString()),
        'reason': value['reason'],
        'originalFrom': value['originalFrom'] == null ? undefined : ((value['originalFrom']).toISOString()),
        'originalUntil': value['originalUntil'] == null ? undefined : ((value['originalUntil']).toISOString()),
    };
}

