/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyTotal
 */
export interface CurrencyTotal {
    /**
     * 
     * @type {string}
     * @memberof CurrencyTotal
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof CurrencyTotal
     */
    amount?: number;
}

/**
 * Check if a given object implements the CurrencyTotal interface.
 */
export function instanceOfCurrencyTotal(value: object): value is CurrencyTotal {
    return true;
}

export function CurrencyTotalFromJSON(json: any): CurrencyTotal {
    return CurrencyTotalFromJSONTyped(json, false);
}

export function CurrencyTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyTotal {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function CurrencyTotalToJSON(json: any): CurrencyTotal {
    return CurrencyTotalToJSONTyped(json, false);
}

export function CurrencyTotalToJSONTyped(value?: CurrencyTotal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'amount': value['amount'],
    };
}

