/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressRequest } from './AddressRequest';
import {
    AddressRequestFromJSON,
    AddressRequestFromJSONTyped,
    AddressRequestToJSON,
    AddressRequestToJSONTyped,
} from './AddressRequest';

/**
 * 
 * @export
 * @interface DepartmentRequest
 */
export interface DepartmentRequest {
    /**
     * 
     * @type {string}
     * @memberof DepartmentRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DepartmentRequest
     */
    description?: string;
    /**
     * 
     * @type {AddressRequest}
     * @memberof DepartmentRequest
     */
    address?: AddressRequest;
}

/**
 * Check if a given object implements the DepartmentRequest interface.
 */
export function instanceOfDepartmentRequest(value: object): value is DepartmentRequest {
    return true;
}

export function DepartmentRequestFromJSON(json: any): DepartmentRequest {
    return DepartmentRequestFromJSONTyped(json, false);
}

export function DepartmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'address': json['address'] == null ? undefined : AddressRequestFromJSON(json['address']),
    };
}

export function DepartmentRequestToJSON(json: any): DepartmentRequest {
    return DepartmentRequestToJSONTyped(json, false);
}

export function DepartmentRequestToJSONTyped(value?: DepartmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'address': AddressRequestToJSON(value['address']),
    };
}

