/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressDTO } from './AddressDTO';
import {
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
    AddressDTOToJSONTyped,
} from './AddressDTO';

/**
 * 
 * @export
 * @interface DepartmentDTO
 */
export interface DepartmentDTO {
    /**
     * 
     * @type {number}
     * @memberof DepartmentDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DepartmentDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DepartmentDTO
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof DepartmentDTO
     */
    companyId?: number;
    /**
     * 
     * @type {AddressDTO}
     * @memberof DepartmentDTO
     */
    address?: AddressDTO;
}

/**
 * Check if a given object implements the DepartmentDTO interface.
 */
export function instanceOfDepartmentDTO(value: object): value is DepartmentDTO {
    return true;
}

export function DepartmentDTOFromJSON(json: any): DepartmentDTO {
    return DepartmentDTOFromJSONTyped(json, false);
}

export function DepartmentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'address': json['address'] == null ? undefined : AddressDTOFromJSON(json['address']),
    };
}

export function DepartmentDTOToJSON(json: any): DepartmentDTO {
    return DepartmentDTOToJSONTyped(json, false);
}

export function DepartmentDTOToJSONTyped(value?: DepartmentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'companyId': value['companyId'],
        'address': AddressDTOToJSON(value['address']),
    };
}

