/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentSummaryDTO
 */
export interface DocumentSummaryDTO {
    /**
     * 
     * @type {number}
     * @memberof DocumentSummaryDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentSummaryDTO
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentSummaryDTO
     */
    currentVersion?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentSummaryDTO
     */
    locked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentSummaryDTO
     */
    lockedBy?: string;
}

/**
 * Check if a given object implements the DocumentSummaryDTO interface.
 */
export function instanceOfDocumentSummaryDTO(value: object): value is DocumentSummaryDTO {
    return true;
}

export function DocumentSummaryDTOFromJSON(json: any): DocumentSummaryDTO {
    return DocumentSummaryDTOFromJSONTyped(json, false);
}

export function DocumentSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'currentVersion': json['currentVersion'] == null ? undefined : json['currentVersion'],
        'locked': json['locked'] == null ? undefined : json['locked'],
        'lockedBy': json['lockedBy'] == null ? undefined : json['lockedBy'],
    };
}

export function DocumentSummaryDTOToJSON(json: any): DocumentSummaryDTO {
    return DocumentSummaryDTOToJSONTyped(json, false);
}

export function DocumentSummaryDTOToJSONTyped(value?: DocumentSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'currentVersion': value['currentVersion'],
        'locked': value['locked'],
        'lockedBy': value['lockedBy'],
    };
}

