/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentGroupRequest
 */
export interface DocumentGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentGroupRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentGroupRequest
     */
    departmentId?: number;
}

/**
 * Check if a given object implements the DocumentGroupRequest interface.
 */
export function instanceOfDocumentGroupRequest(value: object): value is DocumentGroupRequest {
    return true;
}

export function DocumentGroupRequestFromJSON(json: any): DocumentGroupRequest {
    return DocumentGroupRequestFromJSONTyped(json, false);
}

export function DocumentGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'departmentId': json['departmentId'] == null ? undefined : json['departmentId'],
    };
}

export function DocumentGroupRequestToJSON(json: any): DocumentGroupRequest {
    return DocumentGroupRequestToJSONTyped(json, false);
}

export function DocumentGroupRequestToJSONTyped(value?: DocumentGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'departmentId': value['departmentId'],
    };
}

