/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentCheckInRequest
 */
export interface DocumentCheckInRequest {
    /**
     * 
     * @type {Blob}
     * @memberof DocumentCheckInRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the DocumentCheckInRequest interface.
 */
export function instanceOfDocumentCheckInRequest(value: object): value is DocumentCheckInRequest {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function DocumentCheckInRequestFromJSON(json: any): DocumentCheckInRequest {
    return DocumentCheckInRequestFromJSONTyped(json, false);
}

export function DocumentCheckInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCheckInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function DocumentCheckInRequestToJSON(json: any): DocumentCheckInRequest {
    return DocumentCheckInRequestToJSONTyped(json, false);
}

export function DocumentCheckInRequestToJSONTyped(value?: DocumentCheckInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

