/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentGroupDTO
 */
export interface DocumentGroupDTO {
    /**
     * 
     * @type {number}
     * @memberof DocumentGroupDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentGroupDTO
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentGroupDTO
     */
    departmentId?: number;
}

/**
 * Check if a given object implements the DocumentGroupDTO interface.
 */
export function instanceOfDocumentGroupDTO(value: object): value is DocumentGroupDTO {
    return true;
}

export function DocumentGroupDTOFromJSON(json: any): DocumentGroupDTO {
    return DocumentGroupDTOFromJSONTyped(json, false);
}

export function DocumentGroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentGroupDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'departmentId': json['departmentId'] == null ? undefined : json['departmentId'],
    };
}

export function DocumentGroupDTOToJSON(json: any): DocumentGroupDTO {
    return DocumentGroupDTOToJSONTyped(json, false);
}

export function DocumentGroupDTOToJSONTyped(value?: DocumentGroupDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'departmentId': value['departmentId'],
    };
}

