/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentCostLine
 */
export interface EquipmentCostLine {
    /**
     * 
     * @type {number}
     * @memberof EquipmentCostLine
     */
    resourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCostLine
     */
    resourceName?: string;
    /**
     * 
     * @type {number}
     * @memberof EquipmentCostLine
     */
    totalSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof EquipmentCostLine
     */
    bookings?: number;
    /**
     * 
     * @type {number}
     * @memberof EquipmentCostLine
     */
    billedUnits?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCostLine
     */
    unit?: EquipmentCostLineUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof EquipmentCostLine
     */
    rate?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCostLine
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof EquipmentCostLine
     */
    amount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EquipmentCostLine
     */
    running?: boolean;
}


/**
 * @export
 */
export const EquipmentCostLineUnitEnum = {
    Hour: 'HOUR',
    Day: 'DAY',
    Usage: 'USAGE'
} as const;
export type EquipmentCostLineUnitEnum = typeof EquipmentCostLineUnitEnum[keyof typeof EquipmentCostLineUnitEnum];


/**
 * Check if a given object implements the EquipmentCostLine interface.
 */
export function instanceOfEquipmentCostLine(value: object): value is EquipmentCostLine {
    return true;
}

export function EquipmentCostLineFromJSON(json: any): EquipmentCostLine {
    return EquipmentCostLineFromJSONTyped(json, false);
}

export function EquipmentCostLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentCostLine {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'resourceName': json['resourceName'] == null ? undefined : json['resourceName'],
        'totalSeconds': json['totalSeconds'] == null ? undefined : json['totalSeconds'],
        'bookings': json['bookings'] == null ? undefined : json['bookings'],
        'billedUnits': json['billedUnits'] == null ? undefined : json['billedUnits'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'running': json['running'] == null ? undefined : json['running'],
    };
}

export function EquipmentCostLineToJSON(json: any): EquipmentCostLine {
    return EquipmentCostLineToJSONTyped(json, false);
}

export function EquipmentCostLineToJSONTyped(value?: EquipmentCostLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resourceId': value['resourceId'],
        'resourceName': value['resourceName'],
        'totalSeconds': value['totalSeconds'],
        'bookings': value['bookings'],
        'billedUnits': value['billedUnits'],
        'unit': value['unit'],
        'rate': value['rate'],
        'currency': value['currency'],
        'amount': value['amount'],
        'running': value['running'],
    };
}

