/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Correction } from './Correction';
import {
    CorrectionFromJSON,
    CorrectionFromJSONTyped,
    CorrectionToJSON,
    CorrectionToJSONTyped,
} from './Correction';

/**
 * 
 * @export
 * @interface EquipmentSession
 */
export interface EquipmentSession {
    /**
     * 
     * @type {number}
     * @memberof EquipmentSession
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EquipmentSession
     */
    resourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentSession
     */
    resourceName?: string;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentSession
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentSession
     */
    until?: Date;
    /**
     * 
     * @type {number}
     * @memberof EquipmentSession
     */
    seconds?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EquipmentSession
     */
    running?: boolean;
    /**
     * 
     * @type {Correction}
     * @memberof EquipmentSession
     */
    correction?: Correction;
}

/**
 * Check if a given object implements the EquipmentSession interface.
 */
export function instanceOfEquipmentSession(value: object): value is EquipmentSession {
    return true;
}

export function EquipmentSessionFromJSON(json: any): EquipmentSession {
    return EquipmentSessionFromJSONTyped(json, false);
}

export function EquipmentSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentSession {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'resourceName': json['resourceName'] == null ? undefined : json['resourceName'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'until': json['until'] == null ? undefined : (new Date(json['until'])),
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'running': json['running'] == null ? undefined : json['running'],
        'correction': json['correction'] == null ? undefined : CorrectionFromJSON(json['correction']),
    };
}

export function EquipmentSessionToJSON(json: any): EquipmentSession {
    return EquipmentSessionToJSONTyped(json, false);
}

export function EquipmentSessionToJSONTyped(value?: EquipmentSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'resourceId': value['resourceId'],
        'resourceName': value['resourceName'],
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'until': value['until'] == null ? undefined : ((value['until']).toISOString()),
        'seconds': value['seconds'],
        'running': value['running'],
        'correction': CorrectionToJSON(value['correction']),
    };
}

