/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyTotal } from './CurrencyTotal';
import {
    CurrencyTotalFromJSON,
    CurrencyTotalFromJSONTyped,
    CurrencyTotalToJSON,
    CurrencyTotalToJSONTyped,
} from './CurrencyTotal';
import type { EquipmentCostLine } from './EquipmentCostLine';
import {
    EquipmentCostLineFromJSON,
    EquipmentCostLineFromJSONTyped,
    EquipmentCostLineToJSON,
    EquipmentCostLineToJSONTyped,
} from './EquipmentCostLine';

/**
 * 
 * @export
 * @interface EquipmentCostReport
 */
export interface EquipmentCostReport {
    /**
     * 
     * @type {number}
     * @memberof EquipmentCostReport
     */
    taskId?: number;
    /**
     * 
     * @type {Array<EquipmentCostLine>}
     * @memberof EquipmentCostReport
     */
    lines?: Array<EquipmentCostLine>;
    /**
     * 
     * @type {Array<CurrencyTotal>}
     * @memberof EquipmentCostReport
     */
    totals?: Array<CurrencyTotal>;
    /**
     * 
     * @type {boolean}
     * @memberof EquipmentCostReport
     */
    ratesMissing?: boolean;
}

/**
 * Check if a given object implements the EquipmentCostReport interface.
 */
export function instanceOfEquipmentCostReport(value: object): value is EquipmentCostReport {
    return true;
}

export function EquipmentCostReportFromJSON(json: any): EquipmentCostReport {
    return EquipmentCostReportFromJSONTyped(json, false);
}

export function EquipmentCostReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentCostReport {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(EquipmentCostLineFromJSON)),
        'totals': json['totals'] == null ? undefined : ((json['totals'] as Array<any>).map(CurrencyTotalFromJSON)),
        'ratesMissing': json['ratesMissing'] == null ? undefined : json['ratesMissing'],
    };
}

export function EquipmentCostReportToJSON(json: any): EquipmentCostReport {
    return EquipmentCostReportToJSONTyped(json, false);
}

export function EquipmentCostReportToJSONTyped(value?: EquipmentCostReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(EquipmentCostLineToJSON)),
        'totals': value['totals'] == null ? undefined : ((value['totals'] as Array<any>).map(CurrencyTotalToJSON)),
        'ratesMissing': value['ratesMissing'],
    };
}

