/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentSessionRequest
 */
export interface EquipmentSessionRequest {
    /**
     * 
     * @type {Date}
     * @memberof EquipmentSessionRequest
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentSessionRequest
     */
    until?: Date;
    /**
     * 
     * @type {string}
     * @memberof EquipmentSessionRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the EquipmentSessionRequest interface.
 */
export function instanceOfEquipmentSessionRequest(value: object): value is EquipmentSessionRequest {
    return true;
}

export function EquipmentSessionRequestFromJSON(json: any): EquipmentSessionRequest {
    return EquipmentSessionRequestFromJSONTyped(json, false);
}

export function EquipmentSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'until': json['until'] == null ? undefined : (new Date(json['until'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function EquipmentSessionRequestToJSON(json: any): EquipmentSessionRequest {
    return EquipmentSessionRequestToJSONTyped(json, false);
}

export function EquipmentSessionRequestToJSONTyped(value?: EquipmentSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'until': value['until'] == null ? undefined : ((value['until']).toISOString()),
        'reason': value['reason'],
    };
}

