/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentUsageSummary
 */
export interface EquipmentUsageSummary {
    /**
     * 
     * @type {number}
     * @memberof EquipmentUsageSummary
     */
    taskId?: number;
    /**
     * 
     * @type {number}
     * @memberof EquipmentUsageSummary
     */
    resourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUsageSummary
     */
    resourceName?: string;
    /**
     * 
     * @type {number}
     * @memberof EquipmentUsageSummary
     */
    totalSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUsageSummary
     */
    totalText?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EquipmentUsageSummary
     */
    running?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentUsageSummary
     */
    runningSince?: Date;
}

/**
 * Check if a given object implements the EquipmentUsageSummary interface.
 */
export function instanceOfEquipmentUsageSummary(value: object): value is EquipmentUsageSummary {
    return true;
}

export function EquipmentUsageSummaryFromJSON(json: any): EquipmentUsageSummary {
    return EquipmentUsageSummaryFromJSONTyped(json, false);
}

export function EquipmentUsageSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentUsageSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'resourceName': json['resourceName'] == null ? undefined : json['resourceName'],
        'totalSeconds': json['totalSeconds'] == null ? undefined : json['totalSeconds'],
        'totalText': json['totalText'] == null ? undefined : json['totalText'],
        'running': json['running'] == null ? undefined : json['running'],
        'runningSince': json['runningSince'] == null ? undefined : (new Date(json['runningSince'])),
    };
}

export function EquipmentUsageSummaryToJSON(json: any): EquipmentUsageSummary {
    return EquipmentUsageSummaryToJSONTyped(json, false);
}

export function EquipmentUsageSummaryToJSONTyped(value?: EquipmentUsageSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'resourceId': value['resourceId'],
        'resourceName': value['resourceName'],
        'totalSeconds': value['totalSeconds'],
        'totalText': value['totalText'],
        'running': value['running'],
        'runningSince': value['runningSince'] == null ? undefined : ((value['runningSince']).toISOString()),
    };
}

