/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentStopAtRequest
 */
export interface EquipmentStopAtRequest {
    /**
     * 
     * @type {Date}
     * @memberof EquipmentStopAtRequest
     */
    until?: Date;
    /**
     * 
     * @type {string}
     * @memberof EquipmentStopAtRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the EquipmentStopAtRequest interface.
 */
export function instanceOfEquipmentStopAtRequest(value: object): value is EquipmentStopAtRequest {
    return true;
}

export function EquipmentStopAtRequestFromJSON(json: any): EquipmentStopAtRequest {
    return EquipmentStopAtRequestFromJSONTyped(json, false);
}

export function EquipmentStopAtRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentStopAtRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'until': json['until'] == null ? undefined : (new Date(json['until'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function EquipmentStopAtRequestToJSON(json: any): EquipmentStopAtRequest {
    return EquipmentStopAtRequestToJSONTyped(json, false);
}

export function EquipmentStopAtRequestToJSONTyped(value?: EquipmentStopAtRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'until': value['until'] == null ? undefined : ((value['until']).toISOString()),
        'reason': value['reason'],
    };
}

