/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoalProgress
 */
export interface GoalProgress {
    /**
     * 
     * @type {number}
     * @memberof GoalProgress
     */
    goalId?: number;
    /**
     * 
     * @type {string}
     * @memberof GoalProgress
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof GoalProgress
     */
    percentage?: number;
}

/**
 * Check if a given object implements the GoalProgress interface.
 */
export function instanceOfGoalProgress(value: object): value is GoalProgress {
    return true;
}

export function GoalProgressFromJSON(json: any): GoalProgress {
    return GoalProgressFromJSONTyped(json, false);
}

export function GoalProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'goalId': json['goalId'] == null ? undefined : json['goalId'],
        'name': json['name'] == null ? undefined : json['name'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function GoalProgressToJSON(json: any): GoalProgress {
    return GoalProgressToJSONTyped(json, false);
}

export function GoalProgressToJSONTyped(value?: GoalProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goalId': value['goalId'],
        'name': value['name'],
        'percentage': value['percentage'],
    };
}

