/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProjectGoalPropertyDocument } from './ProjectGoalPropertyDocument';
import {
    instanceOfProjectGoalPropertyDocument,
    ProjectGoalPropertyDocumentFromJSON,
    ProjectGoalPropertyDocumentFromJSONTyped,
    ProjectGoalPropertyDocumentToJSON,
} from './ProjectGoalPropertyDocument';
import type { ProjectGoalPropertyNumeric } from './ProjectGoalPropertyNumeric';
import {
    instanceOfProjectGoalPropertyNumeric,
    ProjectGoalPropertyNumericFromJSON,
    ProjectGoalPropertyNumericFromJSONTyped,
    ProjectGoalPropertyNumericToJSON,
} from './ProjectGoalPropertyNumeric';

/**
 * @type GoalRequestPropertiesInner
 * 
 * @export
 */
export type GoalRequestPropertiesInner = ProjectGoalPropertyDocument | ProjectGoalPropertyNumeric;

export function GoalRequestPropertiesInnerFromJSON(json: any): GoalRequestPropertiesInner {
    return GoalRequestPropertiesInnerFromJSONTyped(json, false);
}

export function GoalRequestPropertiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalRequestPropertiesInner {
    if (json == null) {
        return json;
    }
    if (instanceOfProjectGoalPropertyDocument(json)) {
        return ProjectGoalPropertyDocumentFromJSONTyped(json, true);
    }
    if (instanceOfProjectGoalPropertyNumeric(json)) {
        return ProjectGoalPropertyNumericFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GoalRequestPropertiesInnerToJSON(json: any): any {
    return GoalRequestPropertiesInnerToJSONTyped(json, false);
}

export function GoalRequestPropertiesInnerToJSONTyped(value?: GoalRequestPropertiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfProjectGoalPropertyDocument(value)) {
        return ProjectGoalPropertyDocumentToJSON(value as ProjectGoalPropertyDocument);
    }
    if (instanceOfProjectGoalPropertyNumeric(value)) {
        return ProjectGoalPropertyNumericToJSON(value as ProjectGoalPropertyNumeric);
    }

    return {};
}

