/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabourCostLine
 */
export interface LabourCostLine {
    /**
     * 
     * @type {string}
     * @memberof LabourCostLine
     */
    qualificationLevel?: string;
    /**
     * 
     * @type {number}
     * @memberof LabourCostLine
     */
    totalSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof LabourCostLine
     */
    sessions?: number;
    /**
     * 
     * @type {number}
     * @memberof LabourCostLine
     */
    billedUnits?: number;
    /**
     * 
     * @type {string}
     * @memberof LabourCostLine
     */
    unit?: LabourCostLineUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof LabourCostLine
     */
    rate?: number;
    /**
     * 
     * @type {string}
     * @memberof LabourCostLine
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof LabourCostLine
     */
    amount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LabourCostLine
     */
    running?: boolean;
}


/**
 * @export
 */
export const LabourCostLineUnitEnum = {
    Hour: 'HOUR',
    Day: 'DAY',
    Usage: 'USAGE'
} as const;
export type LabourCostLineUnitEnum = typeof LabourCostLineUnitEnum[keyof typeof LabourCostLineUnitEnum];


/**
 * Check if a given object implements the LabourCostLine interface.
 */
export function instanceOfLabourCostLine(value: object): value is LabourCostLine {
    return true;
}

export function LabourCostLineFromJSON(json: any): LabourCostLine {
    return LabourCostLineFromJSONTyped(json, false);
}

export function LabourCostLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabourCostLine {
    if (json == null) {
        return json;
    }
    return {
        
        'qualificationLevel': json['qualificationLevel'] == null ? undefined : json['qualificationLevel'],
        'totalSeconds': json['totalSeconds'] == null ? undefined : json['totalSeconds'],
        'sessions': json['sessions'] == null ? undefined : json['sessions'],
        'billedUnits': json['billedUnits'] == null ? undefined : json['billedUnits'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'running': json['running'] == null ? undefined : json['running'],
    };
}

export function LabourCostLineToJSON(json: any): LabourCostLine {
    return LabourCostLineToJSONTyped(json, false);
}

export function LabourCostLineToJSONTyped(value?: LabourCostLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qualificationLevel': value['qualificationLevel'],
        'totalSeconds': value['totalSeconds'],
        'sessions': value['sessions'],
        'billedUnits': value['billedUnits'],
        'unit': value['unit'],
        'rate': value['rate'],
        'currency': value['currency'],
        'amount': value['amount'],
        'running': value['running'],
    };
}

