/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NfcUnitDTO
 */
export interface NfcUnitDTO {
    /**
     * 
     * @type {number}
     * @memberof NfcUnitDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitDTO
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitDTO
     */
    type?: NfcUnitDTOTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitDTO
     */
    payload?: string;
    /**
     * 
     * @type {number}
     * @memberof NfcUnitDTO
     */
    sequenceNumber?: number;
    /**
     * 
     * @type {Date}
     * @memberof NfcUnitDTO
     */
    lastScanTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof NfcUnitDTO
     */
    resourceId?: number;
    /**
     * 
     * @type {number}
     * @memberof NfcUnitDTO
     */
    boundTaskId?: number;
}


/**
 * @export
 */
export const NfcUnitDTOTypeEnum = {
    Counter: 'COUNTER',
    Checkpoint: 'CHECKPOINT',
    Timetracker: 'TIMETRACKER',
    Infopoint: 'INFOPOINT',
    Other: 'OTHER'
} as const;
export type NfcUnitDTOTypeEnum = typeof NfcUnitDTOTypeEnum[keyof typeof NfcUnitDTOTypeEnum];


/**
 * Check if a given object implements the NfcUnitDTO interface.
 */
export function instanceOfNfcUnitDTO(value: object): value is NfcUnitDTO {
    return true;
}

export function NfcUnitDTOFromJSON(json: any): NfcUnitDTO {
    return NfcUnitDTOFromJSONTyped(json, false);
}

export function NfcUnitDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfcUnitDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'sequenceNumber': json['sequenceNumber'] == null ? undefined : json['sequenceNumber'],
        'lastScanTime': json['lastScanTime'] == null ? undefined : (new Date(json['lastScanTime'])),
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'boundTaskId': json['boundTaskId'] == null ? undefined : json['boundTaskId'],
    };
}

export function NfcUnitDTOToJSON(json: any): NfcUnitDTO {
    return NfcUnitDTOToJSONTyped(json, false);
}

export function NfcUnitDTOToJSONTyped(value?: NfcUnitDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'payload': value['payload'],
        'sequenceNumber': value['sequenceNumber'],
        'lastScanTime': value['lastScanTime'] == null ? undefined : ((value['lastScanTime']).toISOString()),
        'resourceId': value['resourceId'],
        'boundTaskId': value['boundTaskId'],
    };
}

