/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NfcUnitRequest
 */
export interface NfcUnitRequest {
    /**
     * 
     * @type {string}
     * @memberof NfcUnitRequest
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitRequest
     */
    type?: NfcUnitRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NfcUnitRequest
     */
    payload?: string;
}


/**
 * @export
 */
export const NfcUnitRequestTypeEnum = {
    Counter: 'COUNTER',
    Checkpoint: 'CHECKPOINT',
    Timetracker: 'TIMETRACKER',
    Infopoint: 'INFOPOINT',
    Other: 'OTHER'
} as const;
export type NfcUnitRequestTypeEnum = typeof NfcUnitRequestTypeEnum[keyof typeof NfcUnitRequestTypeEnum];


/**
 * Check if a given object implements the NfcUnitRequest interface.
 */
export function instanceOfNfcUnitRequest(value: object): value is NfcUnitRequest {
    return true;
}

export function NfcUnitRequestFromJSON(json: any): NfcUnitRequest {
    return NfcUnitRequestFromJSONTyped(json, false);
}

export function NfcUnitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NfcUnitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function NfcUnitRequestToJSON(json: any): NfcUnitRequest {
    return NfcUnitRequestToJSONTyped(json, false);
}

export function NfcUnitRequestToJSONTyped(value?: NfcUnitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'payload': value['payload'],
    };
}

