/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessInstanceDTO
 */
export interface ProcessInstanceDTO {
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceDTO
     */
    processKey?: string;
    /**
     * 
     * @type {number}
     * @memberof ProcessInstanceDTO
     */
    definitionId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceDTO
     */
    businessKey?: string;
    /**
     * 
     * @type {number}
     * @memberof ProcessInstanceDTO
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessInstanceDTO
     */
    taskId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessInstanceDTO
     */
    running?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProcessInstanceDTO
     */
    startedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceDTO
     */
    startedBy?: string;
}

/**
 * Check if a given object implements the ProcessInstanceDTO interface.
 */
export function instanceOfProcessInstanceDTO(value: object): value is ProcessInstanceDTO {
    return true;
}

export function ProcessInstanceDTOFromJSON(json: any): ProcessInstanceDTO {
    return ProcessInstanceDTOFromJSONTyped(json, false);
}

export function ProcessInstanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessInstanceDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'processKey': json['processKey'] == null ? undefined : json['processKey'],
        'definitionId': json['definitionId'] == null ? undefined : json['definitionId'],
        'businessKey': json['businessKey'] == null ? undefined : json['businessKey'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'running': json['running'] == null ? undefined : json['running'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'startedBy': json['startedBy'] == null ? undefined : json['startedBy'],
    };
}

export function ProcessInstanceDTOToJSON(json: any): ProcessInstanceDTO {
    return ProcessInstanceDTOToJSONTyped(json, false);
}

export function ProcessInstanceDTOToJSONTyped(value?: ProcessInstanceDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'processKey': value['processKey'],
        'definitionId': value['definitionId'],
        'businessKey': value['businessKey'],
        'projectId': value['projectId'],
        'taskId': value['taskId'],
        'running': value['running'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'startedBy': value['startedBy'],
    };
}

