/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoalProgress } from './GoalProgress';
import {
    GoalProgressFromJSON,
    GoalProgressFromJSONTyped,
    GoalProgressToJSON,
    GoalProgressToJSONTyped,
} from './GoalProgress';

/**
 * 
 * @export
 * @interface ProjectProgress
 */
export interface ProjectProgress {
    /**
     * 
     * @type {number}
     * @memberof ProjectProgress
     */
    overallPercentage?: number;
    /**
     * 
     * @type {Array<GoalProgress>}
     * @memberof ProjectProgress
     */
    goals?: Array<GoalProgress>;
}

/**
 * Check if a given object implements the ProjectProgress interface.
 */
export function instanceOfProjectProgress(value: object): value is ProjectProgress {
    return true;
}

export function ProjectProgressFromJSON(json: any): ProjectProgress {
    return ProjectProgressFromJSONTyped(json, false);
}

export function ProjectProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'overallPercentage': json['overallPercentage'] == null ? undefined : json['overallPercentage'],
        'goals': json['goals'] == null ? undefined : ((json['goals'] as Array<any>).map(GoalProgressFromJSON)),
    };
}

export function ProjectProgressToJSON(json: any): ProjectProgress {
    return ProjectProgressToJSONTyped(json, false);
}

export function ProjectProgressToJSONTyped(value?: ProjectProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'overallPercentage': value['overallPercentage'],
        'goals': value['goals'] == null ? undefined : ((value['goals'] as Array<any>).map(GoalProgressToJSON)),
    };
}

