/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDTO
 */
export interface ProjectDTO {
    /**
     * 
     * @type {number}
     * @memberof ProjectDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectDTO
     */
    priority?: number;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDTO
     */
    beginDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDTO
     */
    dueDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ProjectDTO
     */
    maxManDays?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDTO
     */
    managerId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProjectDTO
     */
    memberIds?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ProjectDTO
     */
    blackboardId?: number;
}

/**
 * Check if a given object implements the ProjectDTO interface.
 */
export function instanceOfProjectDTO(value: object): value is ProjectDTO {
    return true;
}

export function ProjectDTOFromJSON(json: any): ProjectDTO {
    return ProjectDTOFromJSONTyped(json, false);
}

export function ProjectDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'dueDate': json['dueDate'] == null ? undefined : (new Date(json['dueDate'])),
        'maxManDays': json['maxManDays'] == null ? undefined : json['maxManDays'],
        'managerId': json['managerId'] == null ? undefined : json['managerId'],
        'memberIds': json['memberIds'] == null ? undefined : json['memberIds'],
        'blackboardId': json['blackboardId'] == null ? undefined : json['blackboardId'],
    };
}

export function ProjectDTOToJSON(json: any): ProjectDTO {
    return ProjectDTOToJSONTyped(json, false);
}

export function ProjectDTOToJSONTyped(value?: ProjectDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'priority': value['priority'],
        'beginDate': value['beginDate'] == null ? undefined : ((value['beginDate']).toISOString().substring(0,10)),
        'dueDate': value['dueDate'] == null ? undefined : ((value['dueDate']).toISOString().substring(0,10)),
        'maxManDays': value['maxManDays'],
        'managerId': value['managerId'],
        'memberIds': value['memberIds'],
        'blackboardId': value['blackboardId'],
    };
}

