/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectRequest
 */
export interface ProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof ProjectRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectRequest
     */
    priority?: number;
    /**
     * 
     * @type {Date}
     * @memberof ProjectRequest
     */
    beginDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectRequest
     */
    dueDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ProjectRequest
     */
    maxManDays?: number;
}

/**
 * Check if a given object implements the ProjectRequest interface.
 */
export function instanceOfProjectRequest(value: object): value is ProjectRequest {
    return true;
}

export function ProjectRequestFromJSON(json: any): ProjectRequest {
    return ProjectRequestFromJSONTyped(json, false);
}

export function ProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'dueDate': json['dueDate'] == null ? undefined : (new Date(json['dueDate'])),
        'maxManDays': json['maxManDays'] == null ? undefined : json['maxManDays'],
    };
}

export function ProjectRequestToJSON(json: any): ProjectRequest {
    return ProjectRequestToJSONTyped(json, false);
}

export function ProjectRequestToJSONTyped(value?: ProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'priority': value['priority'],
        'beginDate': value['beginDate'] == null ? undefined : ((value['beginDate']).toISOString().substring(0,10)),
        'dueDate': value['dueDate'] == null ? undefined : ((value['dueDate']).toISOString().substring(0,10)),
        'maxManDays': value['maxManDays'],
    };
}

