/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectGoalProperty } from './ProjectGoalProperty';
import {
    ProjectGoalPropertyFromJSON,
    ProjectGoalPropertyFromJSONTyped,
    ProjectGoalPropertyToJSON,
    ProjectGoalPropertyToJSONTyped,
} from './ProjectGoalProperty';

/**
 * 
 * @export
 * @interface ProjectGoalPropertyDocument
 */
export interface ProjectGoalPropertyDocument extends ProjectGoalProperty {
    /**
     * 
     * @type {string}
     * @memberof ProjectGoalPropertyDocument
     */
    tag?: string;
}

/**
 * Check if a given object implements the ProjectGoalPropertyDocument interface.
 */
export function instanceOfProjectGoalPropertyDocument(value: object): value is ProjectGoalPropertyDocument {
    return true;
}

export function ProjectGoalPropertyDocumentFromJSON(json: any): ProjectGoalPropertyDocument {
    return ProjectGoalPropertyDocumentFromJSONTyped(json, false);
}

export function ProjectGoalPropertyDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectGoalPropertyDocument {
    if (json == null) {
        return json;
    }
    return {
        ...ProjectGoalPropertyFromJSONTyped(json, true),
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function ProjectGoalPropertyDocumentToJSON(json: any): ProjectGoalPropertyDocument {
    return ProjectGoalPropertyDocumentToJSONTyped(json, false);
}

export function ProjectGoalPropertyDocumentToJSONTyped(value?: ProjectGoalPropertyDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...ProjectGoalPropertyToJSONTyped(value, true),
        'tag': value['tag'],
    };
}

