/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectGoalProperty } from './ProjectGoalProperty';
import {
    ProjectGoalPropertyFromJSON,
    ProjectGoalPropertyFromJSONTyped,
    ProjectGoalPropertyToJSON,
    ProjectGoalPropertyToJSONTyped,
} from './ProjectGoalProperty';

/**
 * 
 * @export
 * @interface ProjectGoalPropertyNumeric
 */
export interface ProjectGoalPropertyNumeric extends ProjectGoalProperty {
    /**
     * 
     * @type {number}
     * @memberof ProjectGoalPropertyNumeric
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectGoalPropertyNumeric
     */
    max?: number;
}

/**
 * Check if a given object implements the ProjectGoalPropertyNumeric interface.
 */
export function instanceOfProjectGoalPropertyNumeric(value: object): value is ProjectGoalPropertyNumeric {
    return true;
}

export function ProjectGoalPropertyNumericFromJSON(json: any): ProjectGoalPropertyNumeric {
    return ProjectGoalPropertyNumericFromJSONTyped(json, false);
}

export function ProjectGoalPropertyNumericFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectGoalPropertyNumeric {
    if (json == null) {
        return json;
    }
    return {
        ...ProjectGoalPropertyFromJSONTyped(json, true),
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
    };
}

export function ProjectGoalPropertyNumericToJSON(json: any): ProjectGoalPropertyNumeric {
    return ProjectGoalPropertyNumericToJSONTyped(json, false);
}

export function ProjectGoalPropertyNumericToJSONTyped(value?: ProjectGoalPropertyNumeric | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...ProjectGoalPropertyToJSONTyped(value, true),
        'min': value['min'],
        'max': value['max'],
    };
}

