/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import { ProjectGoalPropertyDocument, ProjectGoalPropertyDocumentFromJSONTyped, ProjectGoalPropertyDocumentToJSON, ProjectGoalPropertyDocumentToJSONTyped } from './ProjectGoalPropertyDocument';
import { ProjectGoalPropertyNumeric, ProjectGoalPropertyNumericFromJSONTyped, ProjectGoalPropertyNumericToJSON, ProjectGoalPropertyNumericToJSONTyped } from './ProjectGoalPropertyNumeric';
/**
 * 
 * @export
 * @interface ProjectGoalProperty
 */
export interface ProjectGoalProperty {
    /**
     * 
     * @type {number}
     * @memberof ProjectGoalProperty
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectGoalProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGoalProperty
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGoalProperty
     */
    type: string;
}

/**
 * Check if a given object implements the ProjectGoalProperty interface.
 */
export function instanceOfProjectGoalProperty(value: object): value is ProjectGoalProperty {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ProjectGoalPropertyFromJSON(json: any): ProjectGoalProperty {
    return ProjectGoalPropertyFromJSONTyped(json, false);
}

export function ProjectGoalPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectGoalProperty {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'ProjectGoalPropertyDocument') {
            return ProjectGoalPropertyDocumentFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'ProjectGoalPropertyNumeric') {
            return ProjectGoalPropertyNumericFromJSONTyped(json, ignoreDiscriminator);
        }
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'],
    };
}

export function ProjectGoalPropertyToJSON(json: any): ProjectGoalProperty {
    return ProjectGoalPropertyToJSONTyped(json, false);
}

export function ProjectGoalPropertyToJSONTyped(value?: ProjectGoalProperty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['type']) {
            case 'ProjectGoalPropertyDocument':
                return ProjectGoalPropertyDocumentToJSONTyped(value as ProjectGoalPropertyDocument, ignoreDiscriminator);
            case 'ProjectGoalPropertyNumeric':
                return ProjectGoalPropertyNumericToJSONTyped(value as ProjectGoalPropertyNumeric, ignoreDiscriminator);
            default:
                throw new Error(`No variant of ProjectGoalProperty exists with 'type=${value['type']}'`);
        }
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
    };
}

