/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectGoalDTO
 */
export interface ProjectGoalDTO {
    /**
     * 
     * @type {number}
     * @memberof ProjectGoalDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectGoalDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGoalDTO
     */
    description?: string;
}

/**
 * Check if a given object implements the ProjectGoalDTO interface.
 */
export function instanceOfProjectGoalDTO(value: object): value is ProjectGoalDTO {
    return true;
}

export function ProjectGoalDTOFromJSON(json: any): ProjectGoalDTO {
    return ProjectGoalDTOFromJSONTyped(json, false);
}

export function ProjectGoalDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectGoalDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ProjectGoalDTOToJSON(json: any): ProjectGoalDTO {
    return ProjectGoalDTOToJSONTyped(json, false);
}

export function ProjectGoalDTOToJSONTyped(value?: ProjectGoalDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

