/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QualificationLevelDTO
 */
export interface QualificationLevelDTO {
    /**
     * 
     * @type {number}
     * @memberof QualificationLevelDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof QualificationLevelDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof QualificationLevelDTO
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof QualificationLevelDTO
     */
    costRate?: number;
    /**
     * 
     * @type {string}
     * @memberof QualificationLevelDTO
     */
    costCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof QualificationLevelDTO
     */
    costRateUnit?: QualificationLevelDTOCostRateUnitEnum;
}


/**
 * @export
 */
export const QualificationLevelDTOCostRateUnitEnum = {
    Hour: 'HOUR',
    Day: 'DAY',
    Usage: 'USAGE'
} as const;
export type QualificationLevelDTOCostRateUnitEnum = typeof QualificationLevelDTOCostRateUnitEnum[keyof typeof QualificationLevelDTOCostRateUnitEnum];


/**
 * Check if a given object implements the QualificationLevelDTO interface.
 */
export function instanceOfQualificationLevelDTO(value: object): value is QualificationLevelDTO {
    return true;
}

export function QualificationLevelDTOFromJSON(json: any): QualificationLevelDTO {
    return QualificationLevelDTOFromJSONTyped(json, false);
}

export function QualificationLevelDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): QualificationLevelDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'costRate': json['costRate'] == null ? undefined : json['costRate'],
        'costCurrency': json['costCurrency'] == null ? undefined : json['costCurrency'],
        'costRateUnit': json['costRateUnit'] == null ? undefined : json['costRateUnit'],
    };
}

export function QualificationLevelDTOToJSON(json: any): QualificationLevelDTO {
    return QualificationLevelDTOToJSONTyped(json, false);
}

export function QualificationLevelDTOToJSONTyped(value?: QualificationLevelDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'costRate': value['costRate'],
        'costCurrency': value['costCurrency'],
        'costRateUnit': value['costRateUnit'],
    };
}

