/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceValueDTO } from './ResourceValueDTO';
import {
    ResourceValueDTOFromJSON,
    ResourceValueDTOFromJSONTyped,
    ResourceValueDTOToJSON,
    ResourceValueDTOToJSONTyped,
} from './ResourceValueDTO';
import type { TelemetryRuleDTO } from './TelemetryRuleDTO';
import {
    TelemetryRuleDTOFromJSON,
    TelemetryRuleDTOFromJSONTyped,
    TelemetryRuleDTOToJSON,
    TelemetryRuleDTOToJSONTyped,
} from './TelemetryRuleDTO';
import type { ResourceDTO } from './ResourceDTO';
import {
    ResourceDTOFromJSON,
    ResourceDTOFromJSONTyped,
    ResourceDTOToJSON,
    ResourceDTOToJSONTyped,
} from './ResourceDTO';

/**
 * 
 * @export
 * @interface ResourceStatusDTO
 */
export interface ResourceStatusDTO {
    /**
     * 
     * @type {ResourceDTO}
     * @memberof ResourceStatusDTO
     */
    resource?: ResourceDTO;
    /**
     * 
     * @type {Array<ResourceValueDTO>}
     * @memberof ResourceStatusDTO
     */
    latestValues?: Array<ResourceValueDTO>;
    /**
     * 
     * @type {Array<TelemetryRuleDTO>}
     * @memberof ResourceStatusDTO
     */
    telemetryRules?: Array<TelemetryRuleDTO>;
}

/**
 * Check if a given object implements the ResourceStatusDTO interface.
 */
export function instanceOfResourceStatusDTO(value: object): value is ResourceStatusDTO {
    return true;
}

export function ResourceStatusDTOFromJSON(json: any): ResourceStatusDTO {
    return ResourceStatusDTOFromJSONTyped(json, false);
}

export function ResourceStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceStatusDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'resource': json['resource'] == null ? undefined : ResourceDTOFromJSON(json['resource']),
        'latestValues': json['latestValues'] == null ? undefined : ((json['latestValues'] as Array<any>).map(ResourceValueDTOFromJSON)),
        'telemetryRules': json['telemetryRules'] == null ? undefined : ((json['telemetryRules'] as Array<any>).map(TelemetryRuleDTOFromJSON)),
    };
}

export function ResourceStatusDTOToJSON(json: any): ResourceStatusDTO {
    return ResourceStatusDTOToJSONTyped(json, false);
}

export function ResourceStatusDTOToJSONTyped(value?: ResourceStatusDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource': ResourceDTOToJSON(value['resource']),
        'latestValues': value['latestValues'] == null ? undefined : ((value['latestValues'] as Array<any>).map(ResourceValueDTOToJSON)),
        'telemetryRules': value['telemetryRules'] == null ? undefined : ((value['telemetryRules'] as Array<any>).map(TelemetryRuleDTOToJSON)),
    };
}

