/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceValueRequest
 */
export interface ResourceValueRequest {
    /**
     * 
     * @type {string}
     * @memberof ResourceValueRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceValueRequest
     */
    value?: string;
}

/**
 * Check if a given object implements the ResourceValueRequest interface.
 */
export function instanceOfResourceValueRequest(value: object): value is ResourceValueRequest {
    return true;
}

export function ResourceValueRequestFromJSON(json: any): ResourceValueRequest {
    return ResourceValueRequestFromJSONTyped(json, false);
}

export function ResourceValueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceValueRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ResourceValueRequestToJSON(json: any): ResourceValueRequest {
    return ResourceValueRequestToJSONTyped(json, false);
}

export function ResourceValueRequestToJSONTyped(value?: ResourceValueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

