/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceDTO
 */
export interface ResourceDTO {
    /**
     * 
     * @type {number}
     * @memberof ResourceDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDTO
     */
    stationary?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDTO
     */
    remote?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceDTO
     */
    port?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDTO
     */
    busy?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResourceDTO
     */
    maxSlots?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    latitude?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    longitude?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDTO
     */
    mqttResource?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    mqttUUID?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    mqttDataSendTopic?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceDTO
     */
    mqttDataReceiveTopic?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDTO
     */
    mqttOnline?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ResourceDTO
     */
    mqttLastPing?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceDTO
     */
    agent?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResourceDTO
     */
    departmentId?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceDTO
     */
    resourceGroupId?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceDTO
     */
    occupiedSlots?: number;
}

/**
 * Check if a given object implements the ResourceDTO interface.
 */
export function instanceOfResourceDTO(value: object): value is ResourceDTO {
    return true;
}

export function ResourceDTOFromJSON(json: any): ResourceDTO {
    return ResourceDTOFromJSONTyped(json, false);
}

export function ResourceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'stationary': json['stationary'] == null ? undefined : json['stationary'],
        'remote': json['remote'] == null ? undefined : json['remote'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'port': json['port'] == null ? undefined : json['port'],
        'busy': json['busy'] == null ? undefined : json['busy'],
        'maxSlots': json['maxSlots'] == null ? undefined : json['maxSlots'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'mqttResource': json['mqttResource'] == null ? undefined : json['mqttResource'],
        'mqttUUID': json['mqttUUID'] == null ? undefined : json['mqttUUID'],
        'mqttDataSendTopic': json['mqttDataSendTopic'] == null ? undefined : json['mqttDataSendTopic'],
        'mqttDataReceiveTopic': json['mqttDataReceiveTopic'] == null ? undefined : json['mqttDataReceiveTopic'],
        'mqttOnline': json['mqttOnline'] == null ? undefined : json['mqttOnline'],
        'mqttLastPing': json['mqttLastPing'] == null ? undefined : (new Date(json['mqttLastPing'])),
        'agent': json['agent'] == null ? undefined : json['agent'],
        'departmentId': json['departmentId'] == null ? undefined : json['departmentId'],
        'resourceGroupId': json['resourceGroupId'] == null ? undefined : json['resourceGroupId'],
        'occupiedSlots': json['occupiedSlots'] == null ? undefined : json['occupiedSlots'],
    };
}

export function ResourceDTOToJSON(json: any): ResourceDTO {
    return ResourceDTOToJSONTyped(json, false);
}

export function ResourceDTOToJSONTyped(value?: ResourceDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'stationary': value['stationary'],
        'remote': value['remote'],
        'ip': value['ip'],
        'port': value['port'],
        'busy': value['busy'],
        'maxSlots': value['maxSlots'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'mqttResource': value['mqttResource'],
        'mqttUUID': value['mqttUUID'],
        'mqttDataSendTopic': value['mqttDataSendTopic'],
        'mqttDataReceiveTopic': value['mqttDataReceiveTopic'],
        'mqttOnline': value['mqttOnline'],
        'mqttLastPing': value['mqttLastPing'] == null ? undefined : ((value['mqttLastPing']).toISOString()),
        'agent': value['agent'],
        'departmentId': value['departmentId'],
        'resourceGroupId': value['resourceGroupId'],
        'occupiedSlots': value['occupiedSlots'],
    };
}

