/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceCommandRequest
 */
export interface ResourceCommandRequest {
    /**
     * 
     * @type {string}
     * @memberof ResourceCommandRequest
     */
    command?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceCommandRequest
     */
    param?: string;
}

/**
 * Check if a given object implements the ResourceCommandRequest interface.
 */
export function instanceOfResourceCommandRequest(value: object): value is ResourceCommandRequest {
    return true;
}

export function ResourceCommandRequestFromJSON(json: any): ResourceCommandRequest {
    return ResourceCommandRequestFromJSONTyped(json, false);
}

export function ResourceCommandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceCommandRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'] == null ? undefined : json['command'],
        'param': json['param'] == null ? undefined : json['param'],
    };
}

export function ResourceCommandRequestToJSON(json: any): ResourceCommandRequest {
    return ResourceCommandRequestToJSONTyped(json, false);
}

export function ResourceCommandRequestToJSONTyped(value?: ResourceCommandRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
        'param': value['param'],
    };
}

