/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceReservationDTO
 */
export interface ResourceReservationDTO {
    /**
     * 
     * @type {number}
     * @memberof ResourceReservationDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceReservationDTO
     */
    reservedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof ResourceReservationDTO
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ResourceReservationDTO
     */
    until?: Date;
    /**
     * 
     * @type {number}
     * @memberof ResourceReservationDTO
     */
    slotNumber?: number;
}

/**
 * Check if a given object implements the ResourceReservationDTO interface.
 */
export function instanceOfResourceReservationDTO(value: object): value is ResourceReservationDTO {
    return true;
}

export function ResourceReservationDTOFromJSON(json: any): ResourceReservationDTO {
    return ResourceReservationDTOFromJSONTyped(json, false);
}

export function ResourceReservationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceReservationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'reservedBy': json['reservedBy'] == null ? undefined : json['reservedBy'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'until': json['until'] == null ? undefined : (new Date(json['until'])),
        'slotNumber': json['slotNumber'] == null ? undefined : json['slotNumber'],
    };
}

export function ResourceReservationDTOToJSON(json: any): ResourceReservationDTO {
    return ResourceReservationDTOToJSONTyped(json, false);
}

export function ResourceReservationDTOToJSONTyped(value?: ResourceReservationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'reservedBy': value['reservedBy'],
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'until': value['until'] == null ? undefined : ((value['until']).toISOString()),
        'slotNumber': value['slotNumber'],
    };
}

