/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScanResult
 */
export interface ScanResult {
    /**
     * 
     * @type {string}
     * @memberof ScanResult
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ScanResult
     */
    type?: ScanResultTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ScanResult
     */
    action?: string;
    /**
     * 
     * @type {number}
     * @memberof ScanResult
     */
    taskId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ScanResult
     */
    tracking?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ScanResult
     */
    sequenceNumber?: number;
}


/**
 * @export
 */
export const ScanResultTypeEnum = {
    Counter: 'COUNTER',
    Checkpoint: 'CHECKPOINT',
    Timetracker: 'TIMETRACKER',
    Infopoint: 'INFOPOINT',
    Other: 'OTHER'
} as const;
export type ScanResultTypeEnum = typeof ScanResultTypeEnum[keyof typeof ScanResultTypeEnum];


/**
 * Check if a given object implements the ScanResult interface.
 */
export function instanceOfScanResult(value: object): value is ScanResult {
    return true;
}

export function ScanResultFromJSON(json: any): ScanResult {
    return ScanResultFromJSONTyped(json, false);
}

export function ScanResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanResult {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'type': json['type'] == null ? undefined : json['type'],
        'action': json['action'] == null ? undefined : json['action'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'tracking': json['tracking'] == null ? undefined : json['tracking'],
        'sequenceNumber': json['sequenceNumber'] == null ? undefined : json['sequenceNumber'],
    };
}

export function ScanResultToJSON(json: any): ScanResult {
    return ScanResultToJSONTyped(json, false);
}

export function ScanResultToJSONTyped(value?: ScanResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'type': value['type'],
        'action': value['action'],
        'taskId': value['taskId'],
        'tracking': value['tracking'],
        'sequenceNumber': value['sequenceNumber'],
    };
}

