/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillCategoryRequest
 */
export interface SkillCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof SkillCategoryRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillCategoryRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof SkillCategoryRequest
     */
    parentId?: number;
}

/**
 * Check if a given object implements the SkillCategoryRequest interface.
 */
export function instanceOfSkillCategoryRequest(value: object): value is SkillCategoryRequest {
    return true;
}

export function SkillCategoryRequestFromJSON(json: any): SkillCategoryRequest {
    return SkillCategoryRequestFromJSONTyped(json, false);
}

export function SkillCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
    };
}

export function SkillCategoryRequestToJSON(json: any): SkillCategoryRequest {
    return SkillCategoryRequestToJSONTyped(json, false);
}

export function SkillCategoryRequestToJSONTyped(value?: SkillCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'parentId': value['parentId'],
    };
}

