/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillRequest
 */
export interface SkillRequest {
    /**
     * 
     * @type {string}
     * @memberof SkillRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillRequest
     */
    keywords?: string;
    /**
     * 
     * @type {number}
     * @memberof SkillRequest
     */
    categoryId?: number;
}

/**
 * Check if a given object implements the SkillRequest interface.
 */
export function instanceOfSkillRequest(value: object): value is SkillRequest {
    return true;
}

export function SkillRequestFromJSON(json: any): SkillRequest {
    return SkillRequestFromJSONTyped(json, false);
}

export function SkillRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}

export function SkillRequestToJSON(json: any): SkillRequest {
    return SkillRequestToJSONTyped(json, false);
}

export function SkillRequestToJSONTyped(value?: SkillRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'keywords': value['keywords'],
        'categoryId': value['categoryId'],
    };
}

