/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillRecordRequest
 */
export interface SkillRecordRequest {
    /**
     * 
     * @type {number}
     * @memberof SkillRecordRequest
     */
    skillId?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillRecordRequest
     */
    enthusiasm?: number;
}

/**
 * Check if a given object implements the SkillRecordRequest interface.
 */
export function instanceOfSkillRecordRequest(value: object): value is SkillRecordRequest {
    return true;
}

export function SkillRecordRequestFromJSON(json: any): SkillRecordRequest {
    return SkillRecordRequestFromJSONTyped(json, false);
}

export function SkillRecordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillRecordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'skillId': json['skillId'] == null ? undefined : json['skillId'],
        'enthusiasm': json['enthusiasm'] == null ? undefined : json['enthusiasm'],
    };
}

export function SkillRecordRequestToJSON(json: any): SkillRecordRequest {
    return SkillRecordRequestToJSONTyped(json, false);
}

export function SkillRecordRequestToJSONTyped(value?: SkillRecordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skillId': value['skillId'],
        'enthusiasm': value['enthusiasm'],
    };
}

