/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0-SNAPSHOT
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillRecordDTO
 */
export interface SkillRecordDTO {
    /**
     * 
     * @type {number}
     * @memberof SkillRecordDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillRecordDTO
     */
    skillId?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillRecordDTO
     */
    skillName?: string;
    /**
     * 
     * @type {number}
     * @memberof SkillRecordDTO
     */
    enthusiasm?: number;
}

/**
 * Check if a given object implements the SkillRecordDTO interface.
 */
export function instanceOfSkillRecordDTO(value: object): value is SkillRecordDTO {
    return true;
}

export function SkillRecordDTOFromJSON(json: any): SkillRecordDTO {
    return SkillRecordDTOFromJSONTyped(json, false);
}

export function SkillRecordDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillRecordDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'skillId': json['skillId'] == null ? undefined : json['skillId'],
        'skillName': json['skillName'] == null ? undefined : json['skillName'],
        'enthusiasm': json['enthusiasm'] == null ? undefined : json['enthusiasm'],
    };
}

export function SkillRecordDTOToJSON(json: any): SkillRecordDTO {
    return SkillRecordDTOToJSONTyped(json, false);
}

export function SkillRecordDTOToJSONTyped(value?: SkillRecordDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'skillId': value['skillId'],
        'skillName': value['skillName'],
        'enthusiasm': value['enthusiasm'],
    };
}

