/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillCategoryDTO
 */
export interface SkillCategoryDTO {
    /**
     * 
     * @type {number}
     * @memberof SkillCategoryDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillCategoryDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillCategoryDTO
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof SkillCategoryDTO
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillCategoryDTO
     */
    parentName?: string;
}

/**
 * Check if a given object implements the SkillCategoryDTO interface.
 */
export function instanceOfSkillCategoryDTO(value: object): value is SkillCategoryDTO {
    return true;
}

export function SkillCategoryDTOFromJSON(json: any): SkillCategoryDTO {
    return SkillCategoryDTOFromJSONTyped(json, false);
}

export function SkillCategoryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillCategoryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'parentName': json['parentName'] == null ? undefined : json['parentName'],
    };
}

export function SkillCategoryDTOToJSON(json: any): SkillCategoryDTO {
    return SkillCategoryDTOToJSONTyped(json, false);
}

export function SkillCategoryDTOToJSONTyped(value?: SkillCategoryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'parentId': value['parentId'],
        'parentName': value['parentName'],
    };
}

