/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartProcessInstanceRequest
 */
export interface StartProcessInstanceRequest {
    /**
     * 
     * @type {number}
     * @memberof StartProcessInstanceRequest
     */
    definitionId?: number;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof StartProcessInstanceRequest
     */
    variables?: { [key: string]: object; };
}

/**
 * Check if a given object implements the StartProcessInstanceRequest interface.
 */
export function instanceOfStartProcessInstanceRequest(value: object): value is StartProcessInstanceRequest {
    return true;
}

export function StartProcessInstanceRequestFromJSON(json: any): StartProcessInstanceRequest {
    return StartProcessInstanceRequestFromJSONTyped(json, false);
}

export function StartProcessInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartProcessInstanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'definitionId': json['definitionId'] == null ? undefined : json['definitionId'],
        'variables': json['variables'] == null ? undefined : json['variables'],
    };
}

export function StartProcessInstanceRequestToJSON(json: any): StartProcessInstanceRequest {
    return StartProcessInstanceRequestToJSONTyped(json, false);
}

export function StartProcessInstanceRequestToJSONTyped(value?: StartProcessInstanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'definitionId': value['definitionId'],
        'variables': value['variables'],
    };
}

