/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopAtRequest
 */
export interface StopAtRequest {
    /**
     * 
     * @type {Date}
     * @memberof StopAtRequest
     */
    until?: Date;
    /**
     * 
     * @type {string}
     * @memberof StopAtRequest
     */
    reason?: string;
    /**
     * 
     * @type {number}
     * @memberof StopAtRequest
     */
    userId?: number;
}

/**
 * Check if a given object implements the StopAtRequest interface.
 */
export function instanceOfStopAtRequest(value: object): value is StopAtRequest {
    return true;
}

export function StopAtRequestFromJSON(json: any): StopAtRequest {
    return StopAtRequestFromJSONTyped(json, false);
}

export function StopAtRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopAtRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'until': json['until'] == null ? undefined : (new Date(json['until'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function StopAtRequestToJSON(json: any): StopAtRequest {
    return StopAtRequestToJSONTyped(json, false);
}

export function StopAtRequestToJSONTyped(value?: StopAtRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'until': value['until'] == null ? undefined : ((value['until']).toISOString()),
        'reason': value['reason'],
        'userId': value['userId'],
    };
}

