/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskStatusRequest
 */
export interface TaskStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof TaskStatusRequest
     */
    status?: TaskStatusRequestStatusEnum;
}


/**
 * @export
 */
export const TaskStatusRequestStatusEnum = {
    Created: 'CREATED',
    Estimated: 'ESTIMATED',
    Open: 'OPEN',
    Assigned: 'ASSIGNED',
    Started: 'STARTED',
    Stopped: 'STOPPED',
    Finished: 'FINISHED',
    Cancelled: 'CANCELLED',
    Closed: 'CLOSED'
} as const;
export type TaskStatusRequestStatusEnum = typeof TaskStatusRequestStatusEnum[keyof typeof TaskStatusRequestStatusEnum];


/**
 * Check if a given object implements the TaskStatusRequest interface.
 */
export function instanceOfTaskStatusRequest(value: object): value is TaskStatusRequest {
    return true;
}

export function TaskStatusRequestFromJSON(json: any): TaskStatusRequest {
    return TaskStatusRequestFromJSONTyped(json, false);
}

export function TaskStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TaskStatusRequestToJSON(json: any): TaskStatusRequest {
    return TaskStatusRequestToJSONTyped(json, false);
}

export function TaskStatusRequestToJSONTyped(value?: TaskStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

