/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskScheduleDTO
 */
export interface TaskScheduleDTO {
    /**
     * 
     * @type {number}
     * @memberof TaskScheduleDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskScheduleDTO
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskScheduleDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskScheduleDTO
     */
    taskName?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskScheduleDTO
     */
    taskDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskScheduleDTO
     */
    taskPriority?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskScheduleDTO
     */
    cronExpression?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskScheduleDTO
     */
    zoneId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskScheduleDTO
     */
    enabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TaskScheduleDTO
     */
    nextFireAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskScheduleDTO
     */
    lastFiredAt?: Date;
}

/**
 * Check if a given object implements the TaskScheduleDTO interface.
 */
export function instanceOfTaskScheduleDTO(value: object): value is TaskScheduleDTO {
    return true;
}

export function TaskScheduleDTOFromJSON(json: any): TaskScheduleDTO {
    return TaskScheduleDTOFromJSONTyped(json, false);
}

export function TaskScheduleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskScheduleDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'name': json['name'] == null ? undefined : json['name'],
        'taskName': json['taskName'] == null ? undefined : json['taskName'],
        'taskDescription': json['taskDescription'] == null ? undefined : json['taskDescription'],
        'taskPriority': json['taskPriority'] == null ? undefined : json['taskPriority'],
        'cronExpression': json['cronExpression'] == null ? undefined : json['cronExpression'],
        'zoneId': json['zoneId'] == null ? undefined : json['zoneId'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'nextFireAt': json['nextFireAt'] == null ? undefined : (new Date(json['nextFireAt'])),
        'lastFiredAt': json['lastFiredAt'] == null ? undefined : (new Date(json['lastFiredAt'])),
    };
}

export function TaskScheduleDTOToJSON(json: any): TaskScheduleDTO {
    return TaskScheduleDTOToJSONTyped(json, false);
}

export function TaskScheduleDTOToJSONTyped(value?: TaskScheduleDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'name': value['name'],
        'taskName': value['taskName'],
        'taskDescription': value['taskDescription'],
        'taskPriority': value['taskPriority'],
        'cronExpression': value['cronExpression'],
        'zoneId': value['zoneId'],
        'enabled': value['enabled'],
        'nextFireAt': value['nextFireAt'] == null ? undefined : ((value['nextFireAt']).toISOString()),
        'lastFiredAt': value['lastFiredAt'] == null ? undefined : ((value['lastFiredAt']).toISOString()),
    };
}

