/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TelemetryRuleRequest
 */
export interface TelemetryRuleRequest {
    /**
     * 
     * @type {string}
     * @memberof TelemetryRuleRequest
     */
    datapoint?: string;
    /**
     * 
     * @type {string}
     * @memberof TelemetryRuleRequest
     */
    operator?: TelemetryRuleRequestOperatorEnum;
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleRequest
     */
    threshold?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleRequest
     */
    thresholdHigh?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleRequest
     */
    hysteresis?: number;
    /**
     * 
     * @type {string}
     * @memberof TelemetryRuleRequest
     */
    severity?: TelemetryRuleRequestSeverityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TelemetryRuleRequest
     */
    enabled?: boolean;
}


/**
 * @export
 */
export const TelemetryRuleRequestOperatorEnum = {
    Gt: 'GT',
    Lt: 'LT',
    Range: 'RANGE'
} as const;
export type TelemetryRuleRequestOperatorEnum = typeof TelemetryRuleRequestOperatorEnum[keyof typeof TelemetryRuleRequestOperatorEnum];

/**
 * @export
 */
export const TelemetryRuleRequestSeverityEnum = {
    Info: 'INFO',
    Warning: 'WARNING',
    Critical: 'CRITICAL'
} as const;
export type TelemetryRuleRequestSeverityEnum = typeof TelemetryRuleRequestSeverityEnum[keyof typeof TelemetryRuleRequestSeverityEnum];


/**
 * Check if a given object implements the TelemetryRuleRequest interface.
 */
export function instanceOfTelemetryRuleRequest(value: object): value is TelemetryRuleRequest {
    return true;
}

export function TelemetryRuleRequestFromJSON(json: any): TelemetryRuleRequest {
    return TelemetryRuleRequestFromJSONTyped(json, false);
}

export function TelemetryRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelemetryRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'datapoint': json['datapoint'] == null ? undefined : json['datapoint'],
        'operator': json['operator'] == null ? undefined : json['operator'],
        'threshold': json['threshold'] == null ? undefined : json['threshold'],
        'thresholdHigh': json['thresholdHigh'] == null ? undefined : json['thresholdHigh'],
        'hysteresis': json['hysteresis'] == null ? undefined : json['hysteresis'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function TelemetryRuleRequestToJSON(json: any): TelemetryRuleRequest {
    return TelemetryRuleRequestToJSONTyped(json, false);
}

export function TelemetryRuleRequestToJSONTyped(value?: TelemetryRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datapoint': value['datapoint'],
        'operator': value['operator'],
        'threshold': value['threshold'],
        'thresholdHigh': value['thresholdHigh'],
        'hysteresis': value['hysteresis'],
        'severity': value['severity'],
        'enabled': value['enabled'],
    };
}

