/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TelemetryRuleDTO
 */
export interface TelemetryRuleDTO {
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleDTO
     */
    resourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof TelemetryRuleDTO
     */
    datapoint?: string;
    /**
     * 
     * @type {string}
     * @memberof TelemetryRuleDTO
     */
    operator?: TelemetryRuleDTOOperatorEnum;
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleDTO
     */
    threshold?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleDTO
     */
    thresholdHigh?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryRuleDTO
     */
    hysteresis?: number;
    /**
     * 
     * @type {string}
     * @memberof TelemetryRuleDTO
     */
    severity?: TelemetryRuleDTOSeverityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TelemetryRuleDTO
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TelemetryRuleDTO
     */
    state?: TelemetryRuleDTOStateEnum;
    /**
     * 
     * @type {Date}
     * @memberof TelemetryRuleDTO
     */
    lastTransitionAt?: Date;
}


/**
 * @export
 */
export const TelemetryRuleDTOOperatorEnum = {
    Gt: 'GT',
    Lt: 'LT',
    Range: 'RANGE'
} as const;
export type TelemetryRuleDTOOperatorEnum = typeof TelemetryRuleDTOOperatorEnum[keyof typeof TelemetryRuleDTOOperatorEnum];

/**
 * @export
 */
export const TelemetryRuleDTOSeverityEnum = {
    Info: 'INFO',
    Warning: 'WARNING',
    Critical: 'CRITICAL'
} as const;
export type TelemetryRuleDTOSeverityEnum = typeof TelemetryRuleDTOSeverityEnum[keyof typeof TelemetryRuleDTOSeverityEnum];

/**
 * @export
 */
export const TelemetryRuleDTOStateEnum = {
    Ok: 'OK',
    Alarm: 'ALARM'
} as const;
export type TelemetryRuleDTOStateEnum = typeof TelemetryRuleDTOStateEnum[keyof typeof TelemetryRuleDTOStateEnum];


/**
 * Check if a given object implements the TelemetryRuleDTO interface.
 */
export function instanceOfTelemetryRuleDTO(value: object): value is TelemetryRuleDTO {
    return true;
}

export function TelemetryRuleDTOFromJSON(json: any): TelemetryRuleDTO {
    return TelemetryRuleDTOFromJSONTyped(json, false);
}

export function TelemetryRuleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelemetryRuleDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'datapoint': json['datapoint'] == null ? undefined : json['datapoint'],
        'operator': json['operator'] == null ? undefined : json['operator'],
        'threshold': json['threshold'] == null ? undefined : json['threshold'],
        'thresholdHigh': json['thresholdHigh'] == null ? undefined : json['thresholdHigh'],
        'hysteresis': json['hysteresis'] == null ? undefined : json['hysteresis'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'state': json['state'] == null ? undefined : json['state'],
        'lastTransitionAt': json['lastTransitionAt'] == null ? undefined : (new Date(json['lastTransitionAt'])),
    };
}

export function TelemetryRuleDTOToJSON(json: any): TelemetryRuleDTO {
    return TelemetryRuleDTOToJSONTyped(json, false);
}

export function TelemetryRuleDTOToJSONTyped(value?: TelemetryRuleDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'resourceId': value['resourceId'],
        'datapoint': value['datapoint'],
        'operator': value['operator'],
        'threshold': value['threshold'],
        'thresholdHigh': value['thresholdHigh'],
        'hysteresis': value['hysteresis'],
        'severity': value['severity'],
        'enabled': value['enabled'],
        'state': value['state'],
        'lastTransitionAt': value['lastTransitionAt'] == null ? undefined : ((value['lastTransitionAt']).toISOString()),
    };
}

