/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackingSummary
 */
export interface TrackingSummary {
    /**
     * 
     * @type {number}
     * @memberof TrackingSummary
     */
    taskId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TrackingSummary
     */
    tracking?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TrackingSummary
     */
    totalSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackingSummary
     */
    totalText?: string;
    /**
     * 
     * @type {Date}
     * @memberof TrackingSummary
     */
    runningSince?: Date;
}

/**
 * Check if a given object implements the TrackingSummary interface.
 */
export function instanceOfTrackingSummary(value: object): value is TrackingSummary {
    return true;
}

export function TrackingSummaryFromJSON(json: any): TrackingSummary {
    return TrackingSummaryFromJSONTyped(json, false);
}

export function TrackingSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackingSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'tracking': json['tracking'] == null ? undefined : json['tracking'],
        'totalSeconds': json['totalSeconds'] == null ? undefined : json['totalSeconds'],
        'totalText': json['totalText'] == null ? undefined : json['totalText'],
        'runningSince': json['runningSince'] == null ? undefined : (new Date(json['runningSince'])),
    };
}

export function TrackingSummaryToJSON(json: any): TrackingSummary {
    return TrackingSummaryToJSONTyped(json, false);
}

export function TrackingSummaryToJSONTyped(value?: TrackingSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'tracking': value['tracking'],
        'totalSeconds': value['totalSeconds'],
        'totalText': value['totalText'],
        'runningSince': value['runningSince'] == null ? undefined : ((value['runningSince']).toISOString()),
    };
}

