/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressRequest } from './AddressRequest';
import {
    AddressRequestFromJSON,
    AddressRequestFromJSONTyped,
    AddressRequestToJSON,
    AddressRequestToJSONTyped,
} from './AddressRequest';

/**
 * 
 * @export
 * @interface UserRequest
 */
export interface UserRequest {
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    occupation?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserRequest
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    gender?: UserRequestGenderEnum;
    /**
     * 
     * @type {AddressRequest}
     * @memberof UserRequest
     */
    address?: AddressRequest;
    /**
     * 
     * @type {boolean}
     * @memberof UserRequest
     */
    admin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserRequest
     */
    active?: boolean;
}


/**
 * @export
 */
export const UserRequestGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Other: 'OTHER',
    TechnicalUser: 'TECHNICAL_USER'
} as const;
export type UserRequestGenderEnum = typeof UserRequestGenderEnum[keyof typeof UserRequestGenderEnum];


/**
 * Check if a given object implements the UserRequest interface.
 */
export function instanceOfUserRequest(value: object): value is UserRequest {
    return true;
}

export function UserRequestFromJSON(json: any): UserRequest {
    return UserRequestFromJSONTyped(json, false);
}

export function UserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'name': json['name'] == null ? undefined : json['name'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'email': json['email'] == null ? undefined : json['email'],
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : (new Date(json['dateOfBirth'])),
        'gender': json['gender'] == null ? undefined : json['gender'],
        'address': json['address'] == null ? undefined : AddressRequestFromJSON(json['address']),
        'admin': json['admin'] == null ? undefined : json['admin'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function UserRequestToJSON(json: any): UserRequest {
    return UserRequestToJSONTyped(json, false);
}

export function UserRequestToJSONTyped(value?: UserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'name': value['name'],
        'firstname': value['firstname'],
        'email': value['email'],
        'occupation': value['occupation'],
        'dateOfBirth': value['dateOfBirth'] == null ? undefined : ((value['dateOfBirth']).toISOString().substring(0,10)),
        'gender': value['gender'],
        'address': AddressRequestToJSON(value['address']),
        'admin': value['admin'],
        'active': value['active'],
    };
}

