/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkSession
 */
export interface WorkSession {
    /**
     * 
     * @type {Date}
     * @memberof WorkSession
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkSession
     */
    until?: Date;
    /**
     * 
     * @type {number}
     * @memberof WorkSession
     */
    seconds?: number;
    /**
     * 
     * @type {boolean}
     * @memberof WorkSession
     */
    running?: boolean;
}

/**
 * Check if a given object implements the WorkSession interface.
 */
export function instanceOfWorkSession(value: object): value is WorkSession {
    return true;
}

export function WorkSessionFromJSON(json: any): WorkSession {
    return WorkSessionFromJSONTyped(json, false);
}

export function WorkSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkSession {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'until': json['until'] == null ? undefined : (new Date(json['until'])),
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'running': json['running'] == null ? undefined : json['running'],
    };
}

export function WorkSessionToJSON(json: any): WorkSession {
    return WorkSessionToJSONTyped(json, false);
}

export function WorkSessionToJSONTyped(value?: WorkSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'until': value['until'] == null ? undefined : ((value['until']).toISOString()),
        'seconds': value['seconds'],
        'running': value['running'],
    };
}

