/* tslint:disable */
/* eslint-disable */
/**
 * Prioritize API
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked \'experimental\' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: peter.haller@prioritize-iot.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkSessionRequest
 */
export interface WorkSessionRequest {
    /**
     * 
     * @type {Date}
     * @memberof WorkSessionRequest
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkSessionRequest
     */
    until?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkSessionRequest
     */
    reason?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkSessionRequest
     */
    userId?: number;
}

/**
 * Check if a given object implements the WorkSessionRequest interface.
 */
export function instanceOfWorkSessionRequest(value: object): value is WorkSessionRequest {
    return true;
}

export function WorkSessionRequestFromJSON(json: any): WorkSessionRequest {
    return WorkSessionRequestFromJSONTyped(json, false);
}

export function WorkSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'until': json['until'] == null ? undefined : (new Date(json['until'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function WorkSessionRequestToJSON(json: any): WorkSessionRequest {
    return WorkSessionRequestToJSONTyped(json, false);
}

export function WorkSessionRequestToJSONTyped(value?: WorkSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'until': value['until'] == null ? undefined : ((value['until']).toISOString()),
        'reason': value['reason'],
        'userId': value['userId'],
    };
}

